items = {
        ## None
        'nothing'                   : {"type" : "", "attack" : 0, "defense" : 0, "value" : 0, "rarity" : 0, "count" : 0},
        
        ## Consumable

        # Material
        'iron ingot'                : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'steel ingot'               : {"type" : "material", "value" : 125, "rarity" : 0, "count" : 1},
        'copper ingot'              : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'bronze ingot'              : {"type" : "material", "value" : 125, "rarity" : 0, "count" : 1},
        'silver ingot'              : {"type" : "material", "value" : 250, "rarity" : 0, "count" : 1},
        'gold ingot'                : {"type" : "material", "value" : 1250, "rarity" : 0, "count" : 1},
        'mythril ingot'             : {"type" : "material", "value" : 5000, "rarity" : 0, "count" : 1},
        'iron bar'                  : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'steel bar'                 : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'copper bar'                : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'bronze bar'                : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'silver bar'                : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'gold bar'                  : {"type" : "material", "value" : 250, "rarity" : 0, "count" : 1},
        'mythril bar'               : {"type" : "material", "value" : 1000, "rarity" : 0, "count" : 1},
        'iron rod'                  : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1},
        'steel rod'                 : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'copper rod'                : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1},
        'bronze rod'                : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'silver rod'                : {"type" : "material", "value" : 100, "rarity" : 0, "count" : 1},
        'gold rod'                  : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1},
        'mythril rod'               : {"type" : "material", "value" : 2000, "rarity" : 0, "count" : 1},
        'iron wire'                 : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1},
        'steel wire'                : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'copper wire'               : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1},
        'bronze wire'               : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'silver wire'               : {"type" : "material", "value" : 100, "rarity" : 0, "count" : 1},
        'gold wire'                 : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1},
        'mythril wire'              : {"type" : "material", "value" : 2000, "rarity" : 0, "count" : 1},
        'wood'                      : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'ent wood'                  : {"type" : "material", "value" : 250, "rarity" : 0, "count" : 1},
        'cloth'                     : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'rope'                      : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'string'                    : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'leather'                   : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'wyvern hide'               : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1},
        'dragon hide'               : {"type" : "material", "value" : 1000, "rarity" : 0, "count" : 1},
        'gargoyle fang'             : {"type" : "material", "value" : 100, "rarity" : 0, "count" : 1},
        'wyvern fang'               : {"type" : "material", "value" : 250, "rarity" : 0, "count" : 1},
        'dragon fang'               : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1},
        'raw meat'                  : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'raw fish'                  : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'flax'                      : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},

        # Food
        'porridge'                  : {"type" : "food", "hp" : 5, "mp" : 5, "value" : 25, "rarity" : 150, "count" : 2},
        'haggis'                    : {"type" : "food", "hp" : 15, "mp" : 15, "value" : 50, "rarity" : 50, "count" : 5},
        'bread'                     : {"type" : "food", "hp" : 5, "mp" : 5, "value" : 25, "rarity" : 150, "count" : 2},
		'kebab'                     : {"type" : "food", "hp" : 10, "mp" : 10, "value" : 50, "rarity" : 50, "count" : 5},
        'fish'                      : {"type" : "food", "hp" : 10, "mp" : 10, "value" : 25, "rarity" : 50, "count" : 5},
        'steak'                     : {"type" : "food", "hp" : 15, "mp" : 15, "value" : 50, "rarity" : 50, "count" : 5},
        'soup'                      : {"type" : "food", "hp" : 10, "mp" : 10, "value" : 25, "rarity" : 100, "count" : 4},
        'stew'                      : {"type" : "food", "hp" : 15, "mp" : 15, "value" : 25, "rarity" : 100, "count" : 4},

        # Potion
        'minor health potion'       : {"type" : "potion", "hp" : 10, "value" : 500, "rarity" : 250, "count" : 10},
        'health potion'             : {"type" : "potion", "hp" : 25, "value" : 250, "rarity" : 100, "count" : 5},
        'major health potion'       : {"type" : "potion", "hp" : 50, "value" : 100, "rarity" : 50, "count" : 2},
        'minor mana potion'         : {"type" : "potion", "mp" : 10, "value" : 500, "rarity" : 250, "count" : 10},
        'mana potion'               : {"type" : "potion", "mp" : 25, "value" : 250, "rarity" : 100, "count" : 5},
        'major mana potion'         : {"type" : "potion", "mp" : 50, "value" : 100, "rarity" : 50, "count" : 2},
        'elixer'                    : {"type" : "potion", "hp" : 25, "mp" : 25, "value" : 250, "rarity" : 100, "count" : 5},
        'restoration potion'        : {"type" : "potion", "hp" : 10000000, "mp" : 10000000, "value" : 1000, "rarity" : 50, "count" : 2},
        'potion of blessings'       : {"type" : "potion", "mag" : 1, "atk" : 1, "def" : 1, "value" : 50000, "rarity" : 1, "count" : 2},
        'potion of magic'           : {"type" : "potion", "mag" : 1, "value" : 25000, "rarity" : 2, "count" : 2},
        'potion of attack'          : {"type" : "potion", "atk" : 1, "value" : 25000, "rarity" : 2, "count" : 2},
        'potion of defense'         : {"type" : "potion", "def" : 1, "value" : 25000, "rarity" : 2, "count" : 2},
        'potion of health'          : {"type" : "potion", "HP" : 1, "value" : 25000, "rarity" : 5, "count" : 2},
        'potion of mana'            : {"type" : "potion", "MP" : 1, "value" : 25000, "rarity" : 5, "count" : 2},

        # Scroll
        #
        'scroll of firestorm'         : {"type" : "scroll", "spell" : "firestorm", "value" : 5000, "rarity" : 5, "count" : 2},
        'scroll of lightning barrage' : {"type" : "scroll", "spell" : "lightning barrage", "value" : 5000, "rarity" : 5, "count" : 2},
        'scroll of tsunami'           : {"type" : "scroll", "spell" : "tsunami", "value" : 5000, "rarity" : 5, "count" : 2},
        'scroll of earthquake'        : {"type" : "scroll", "spell" : "earthquake", "value" : 5000, "rarity" : 5, "count" : 2},
        'scroll of destroy'           : {"type" : "scroll", "spell" : "destroy", "value" : 5000, "rarity" : 5, "count" : 2},
        #
        'scroll of fireblast'         : {"type" : "scroll", "spell" : "fireblast", "value" : 2500, "rarity" : 10, "count" : 2},
        'scroll of lightning'         : {"type" : "scroll", "spell" : "lightning", "value" : 2500, "rarity" : 10, "count" : 2},
        'scroll of flash flood'       : {"type" : "scroll", "spell" : "flash flood", "value" : 2500, "rarity" : 10, "count" : 2},
        'scroll of fissure'           : {"type" : "scroll", "spell" : "fissure", "value" : 2500, "rarity" : 10, "count" : 2},
        'scroll of kill'              : {"type" : "scroll", "spell" : "kill", "value" : 2500, "rarity" : 10, "count" : 2},
        #
        'scroll of fireball'          : {"type" : "scroll", "spell" : "fireball", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of lightning bolt'    : {"type" : "scroll", "spell" : "lightning bolt", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of water burst'       : {"type" : "scroll", "spell" : "water burst", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of ground collapse'   : {"type" : "scroll", "spell" : "ground collapse", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of harm'              : {"type" : "scroll", "spell" : "harm", "value" : 1000, "rarity" : 25, "count" : 2},
        #
        'scroll of burn'              : {"type" : "scroll", "spell" : "burn", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of electric shock'    : {"type" : "scroll", "spell" : "electric shock", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of poison rain'       : {"type" : "scroll", "spell" : "poison rain", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of tremor'            : {"type" : "scroll", "spell" : "tremor", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of decay'             : {"type" : "scroll", "spell" : "decay", "value" : 1000, "rarity" : 25, "count" : 2},
        #
        'scroll of heal'              : {"type" : "scroll", "spell" : "heal", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of heal all'          : {"type" : "scroll", "spell" : "heal all", "value" : 2500, "rarity" : 5, "count" : 2},
        'scroll of cure'              : {"type" : "scroll", "spell" : "cure", "value" : 2500, "rarity" : 10, "count" : 2},
        'scroll of cure all'          : {"type" : "scroll", "spell" : "cure all", "value" : 5000, "rarity" : 5, "count" : 2},
        'scroll of cure poison'       : {"type" : "scroll", "spell" : "cure poison", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of cure confusion'    : {"type" : "scroll", "spell" : "cure confusion", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of cure stun'         : {"type" : "scroll", "spell" : "cure stun", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of cure burn'         : {"type" : "scroll", "spell" : "cure burn", "value" : 1000, "rarity" : 25, "count" : 2},
        #
        'scroll of inflict poison'    : {"type" : "scroll", "spell" : "inflict poison", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of inflict confusion' : {"type" : "scroll", "spell" : "inflict confusion", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of inflict stun'      : {"type" : "scroll", "spell" : "inflict stun", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of inflict burn'      : {"type" : "scroll", "spell" : "inflict burn", "value" : 1000, "rarity" : 25, "count" : 2},
        
        ## Arms
        
        # Bludgeon
        'club'                       : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'club +1'                    : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'club +2'                    : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'spiked club'                : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 100, "rarity" : 200, "count" : 2, "slot" : " hand"},
        'spiked club +1'             : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 100, "rarity" : 200, "count" : 2, "slot" : " hand"},
        'spiked club +2'             : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 100, "rarity" : 200, "count" : 2, "slot" : " hand"},
        'mace'                       : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'mace +1'                    : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'mace +2'                    : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'greatmace'                  : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'greatmace +1'               : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'greatmace +2'               : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'morning star'               : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'morning star +1'            : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'morning star +2'            : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'war hammer'                 : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'war hammer +1'              : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'war hammer +2'              : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        # Axe
        'war axe'                    : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'war axe +1'                 : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'war axe +2'                 : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'great war axe'              : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'great war axe +1'           : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'great war axe +2'           : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'igorot'                     : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'igorot +1'                  : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'igorot +2'                  : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'lochaber axe'               : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'lochaber axe +1'            : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'lochaber axe +2'            : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'bardiche'                   : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'bardiche +1'                : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'bardiche +2'                : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'halberd'                    : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'halberd +1'                 : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'halberd +2'                 : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        # Dagger
        'dagger'                     : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'dagger +1'                  : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'dagger +2'                  : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'athame'                     : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'athame +1'                  : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'athame +2'                  : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pugio'                      : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pugio +1'                   : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pugio +2'                   : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'cinquedea'                  : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'cinquedea +1'               : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'cinquedea +2'               : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'dirk'                       : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'dirk +1'                    : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'dirk +2'                    : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'acinaces'                   : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'acinaces +1'                : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'acinaces +2'                : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'anelace'                    : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'anelace +1'                 : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'anelace +2'                 : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        # Knife
        'kiridashi'                  : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kiridashi +1'               : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kiridashi +2'               : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'karambit'                   : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'karambit +1'                : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'karambit +2'                : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'puuko'                      : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'puuko +1'                   : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'puuko +2'                   : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'sgian dubh'                 : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'sgian dubh +1'              : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'sgian dubh +2'              : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'tanto'                      : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'tanto +1'                   : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'tanto +2'                   : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kirpan'                     : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kirpan +1'                  : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kirpan +2'                  : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'seax'                       : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'seax +1'                    : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'seax +2'                    : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kukri'                      : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kukri +1'                   : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kukri +2'                   : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'machete'                    : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'machete +1'                 : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'machete +2'                 : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        # Sword
        'bastardsword'               : {"type" : "arms", "attack" : 3, "defense" : 2, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'bastardsword +1'            : {"type" : "arms", "attack" : 3, "defense" : 2, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'bastardsword +2'            : {"type" : "arms", "attack" : 3, "defense" : 2, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'shortsword'                 : {"type" : "arms", "attack" : 2, "defense" : 1, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'shortsword +1'              : {"type" : "arms", "attack" : 2, "defense" : 1, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'shortsword +2'              : {"type" : "arms", "attack" : 2, "defense" : 1, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'longsword'                  : {"type" : "arms", "attack" : 3, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'longsword +1'               : {"type" : "arms", "attack" : 3, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'longsword +2'               : {"type" : "arms", "attack" : 3, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'rapier'                     : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'rapier +1'                  : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'rapier +2'                  : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'sabre'                      : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'sabre +1'                   : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'sabre +2'                   : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'falchion'                   : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'falchion +1'                : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'falchion +2'                : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'scimitar'                   : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'scimitar +1'                : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'scimitar +2'                : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopesh'                     : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopesh +1'                  : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopesh +2'                  : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopis'                      : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopis +1'                   : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopis +2'                   : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'katana'                     : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'katana +1'                  : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'katana +2'                  : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        # Great Sword
        'uchigatana'                 : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'uchigatana +1'              : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'uchigatana +2'              : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'greatsword'                 : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'greatsword +1'              : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'greatsword +2'              : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'claymore'                   : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'claymore +1'                : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'claymore +2'                : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'flamberge'                  : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'flamberge +1'               : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'flamberge +2'               : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        # Polearm
        'hunting spear'              : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'hunting spear +1'           : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'hunting spear +2'           : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'spear'                      : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'spear +1'                   : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'spear +2'                   : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pike'                       : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pike +1'                    : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pike +2'                    : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'lance'                      : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'lance +1'                   : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'lance +2'                   : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'voulge'                     : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'voulge +1'                  : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'voulge +2'                  : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        # Shield
        'buckler'                    : {"type" : "arms", "attack" : 1, "defense" : 1, "value" : 50, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'buckler +1'                 : {"type" : "arms", "attack" : 1, "defense" : 1, "value" : 50, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'buckler +2'                 : {"type" : "arms", "attack" : 1, "defense" : 1, "value" : 50, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'shield'                     : {"type" : "arms", "attack" : 1, "defense" : 2, "value" : 100, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'shield +1'                  : {"type" : "arms", "attack" : 1, "defense" : 2, "value" : 100, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'shield +2'                  : {"type" : "arms", "attack" : 1, "defense" : 2, "value" : 100, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'tower shield'               : {"type" : "arms", "attack" : 1, "defense" : 4, "value" : 250, "rarity" : 25, "count" : 2, "slot" : " hand"},
        'tower shield +1'            : {"type" : "arms", "attack" : 1, "defense" : 4, "value" : 250, "rarity" : 25, "count" : 2, "slot" : " hand"},
        'tower shield +2'            : {"type" : "arms", "attack" : 1, "defense" : 4, "value" : 250, "rarity" : 25, "count" : 2, "slot" : " hand"},
        # Ranged
        'flintlock pistol'           : {"type" : "arms", "attack" : 6, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'flintlock pistol +1'        : {"type" : "arms", "attack" : 6, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'flintlock pistol +2'        : {"type" : "arms", "attack" : 6, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver'                   : {"type" : "arms", "attack" : 6, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver +1'                : {"type" : "arms", "attack" : 6, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver +2'                : {"type" : "arms", "attack" : 6, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'flintlock rifle'            : {"type" : "arms", "attack" : 8, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'flintlock rifle +1'         : {"type" : "arms", "attack" : 8, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'flintlock rifle +2'         : {"type" : "arms", "attack" : 8, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver rifle'             : {"type" : "arms", "attack" : 8, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver rifle +1'          : {"type" : "arms", "attack" : 8, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver rifle +2'          : {"type" : "arms", "attack" : 8, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        
        ## Armor
        
        # Necklace
        'necklace'                   : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 500, "rarity" : 5, "count" : 2, "slot" : "neck"},
        'magic necklace'             : {"type" : "armor", "magic" : 1, "attack" : 0, "defense" : 0, "value" : 2500, "rarity" : 2, "count" : 2, "slot" : "neck"},
        'magic necklace +1'          : {"type" : "armor", "magic" : 2, "attack" : 0, "defense" : 0, "value" : 5000, "rarity" : 2, "count" : 2, "slot" : "neck"},
        'magic necklace +2'          : {"type" : "armor", "magic" : 3, "attack" : 0, "defense" : 0, "value" : 7500, "rarity" : 2, "count" : 2, "slot" : "neck"},
        'blessed necklace'           : {"type" : "armor", "magic" : 1, "attack" : 1, "defense" : 1, "value" : 2500, "rarity" : 1, "count" : 2, "slot" : "neck"},
        'blessed necklace +1'        : {"type" : "armor", "magic" : 2, "attack" : 2, "defense" : 2, "value" : 5000, "rarity" : 1, "count" : 2, "slot" : "neck"},
        'blessed necklace +2'        : {"type" : "armor", "magic" : 3, "attack" : 3, "defense" : 3, "value" : 7500, "rarity" : 1, "count" : 2, "slot" : "neck"},
        # Rings
        'ring'                       : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 500, "rarity" : 5, "count" : 2, "slot" : "ring"},
        'magic ring'                 : {"type" : "armor", "magic" : 1, "attack" : 0, "defense" : 0, "value" : 2500, "rarity" : 2, "count" : 2, "slot" : "ring"},
        'magic ring +1'              : {"type" : "armor", "magic" : 2, "attack" : 0, "defense" : 0, "value" : 5000, "rarity" : 2, "count" : 2, "slot" : "ring"},
        'magic ring +2'              : {"type" : "armor", "magic" : 3, "attack" : 0, "defense" : 0, "value" : 7500, "rarity" : 2, "count" : 2, "slot" : "ring"},
        'blessed ring'               : {"type" : "armor", "magic" : 1, "attack" : 1, "defense" : 1, "value" : 2500, "rarity" : 1, "count" : 2, "slot" : "ring"},
        'blessed ring +1'            : {"type" : "armor", "magic" : 2, "attack" : 2, "defense" : 2, "value" : 5000, "rarity" : 1, "count" : 2, "slot" : "ring"},
        'blessed ring +2'            : {"type" : "armor", "magic" : 3, "attack" : 3, "defense" : 3, "value" : 7500, "rarity" : 1, "count" : 2, "slot" : "ring"},
        # Head
        'coif'                       : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 200, "rarity" : 15, "count" : 2, "slot" : "head"},
        'coif +1'                    : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 400, "rarity" : 0, "count" : 2, "slot" : "head"},
        'coif +2'                    : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 600, "rarity" : 0, "count" : 2, "slot" : "head"},
        'cervelliere'                : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 150, "rarity" : 15, "count" : 2, "slot" : "head"},
        'cervelliere +1'             : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "head"},
        'cervelliere +2'             : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 450, "rarity" : 0, "count" : 2, "slot" : "head"},
        'nasal helm'                 : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 150, "rarity" : 15, "count" : 2, "slot" : "head"},
        'nasal helm +1'              : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "head"},
        'nasal helm +2'              : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 450, "rarity" : 0, "count" : 2, "slot" : "head"},
        'sallet'                     : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 200, "rarity" : 15, "count" : 2, "slot" : "head"},
        'sallet +1'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 400, "rarity" : 0, "count" : 2, "slot" : "head"},
        'sallet +2'                  : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 600, "rarity" : 0, "count" : 2, "slot" : "head"},
        'barbute'                    : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 250, "rarity" : 15, "count" : 2, "slot" : "head"},
        'barbute +1'                 : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "head"},
        'barbute +2'                 : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "head"},
        'greathelm'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 250, "rarity" : 10, "count" : 2, "slot" : "head"},
        'greathelm +1'               : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "head"},
        'greathelm +2'               : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "head"},
        'bassinet'                   : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 250, "rarity" : 15, "count" : 2, "slot" : "head"},
        'bassinet +1'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "head"},
        'bassinet +2'                : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "head"},
        'close helm'                 : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 250, "rarity" : 15, "count" : 2, "slot" : "head"},
        'close helm +1'              : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "head"},
        'close helm +2'              : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "head"},
        # Neck
        'cloak'                      : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 100, "rarity" : 25, "count" : 3, "slot" : "neck"},
        'bevor'                      : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 250, "rarity" : 10, "count" : 3, "slot" : "neck"},
        'bevor +1'                   : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 0, "count" : 3, "slot" : "neck"},
        'bevor +2'                   : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 0, "count" : 3, "slot" : "neck"},
        'gorget'                     : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 250, "rarity" : 10, "count" : 3, "slot" : "neck"},
        'gorget +1'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 0, "count" : 3, "slot" : "neck"},
        'gorget +2'                  : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 0, "count" : 3, "slot" : "neck"},
        # Shoulders
        'spaulders'                  : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 3, "slot" : "shoulders"},
        'spaulders +1'               : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 200, "rarity" : 0, "count" : 3, "slot" : "shoulders"},
        'spaulders +2'               : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 300, "rarity" : 0, "count" : 3, "slot" : "shoulders"},
        'pauldrons'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 100, "rarity" : 25, "count" : 3, "slot" : "shoulders"},
        'pauldrons +1'               : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 3, "slot" : "shoulders"},
        'pauldrons +2'               : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 0, "count" : 3, "slot" : "shoulders"},
        # Torso
        'shirt'                      : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 25, "rarity" : 75, "count" : 2, "slot" : "torso"},
        'ringmail'                   : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 15, "count" : 2, "slot" : "torso"},
        'ringmail +1'                : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 1000, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'ringmail +2'                : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'hauberk'                    : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 10, "count" : 2, "slot" : "torso"},
        'hauberk +1'                 : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'hauberk +2'                 : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 2250, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'breastplate'                : {"type" : "armor", "attack" : 0, "defense" : 5, "value" : 1000, "rarity" : 5, "count" : 2, "slot" : "torso"},
        'breastplate +1'             : {"type" : "armor", "attack" : 0, "defense" : 5, "value" : 2000, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'breastplate +2'             : {"type" : "armor", "attack" : 0, "defense" : 5, "value" : 3000, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'coat of plates'             : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 5, "count" : 2, "slot" : "torso"},
        'coat of plates +1'          : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'coat of plates +2'          : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 2250, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'cuirass'                    : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 5, "count" : 2, "slot" : "torso"},
        'cuirass +1'                 : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'cuirass +2'                 : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 2250, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'leather cuirass'            : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 5, "count" : 2, "slot" : "torso"},
        'leather cuirass +1'         : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 1000, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'leather cuirass +2'         : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'studded leather cuirass'    : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 5, "count" : 2, "slot" : "torso"},
        'studded leather cuirass +1' : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'studded leather cuirass +2' : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 2250, "rarity" : 0, "count" : 2, "slot" : "torso"},
        # Waist
        'belt'                       : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 50, "rarity" : 100, "count" : 2, "slot" : "waist"},
        'chainskirt'                 : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 50, "count" : 2, "slot" : "waist"},
        'chainskirt +1'              : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "waist"},
        'chainskirt +2'              : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "waist"},
        'tassets'                    : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 50, "count" : 2, "slot" : "waist"},
        'tassets +1'                 : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "waist"},
        'tassets +2'                 : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "waist"},
        'fauld'                      : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "waist"},
        'fauld +1'                   : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "waist"},
        'fauld +2'                   : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "waist"},
        # Arms
        'bracers'                    : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "arms"},
        'bracers +1'                 : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'bracers +2'                 : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'vambrace'                   : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "arms"},
        'vambrace +1'                : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'vambrace +2'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'rerebrace'                  : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "arms"},
        'rerebrace +1'               : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'rerebrace +2'               : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'full cannon'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 250, "rarity" : 25, "count" : 2, "slot" : "arms"},
        'full cannon +1'             : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'full cannon +2'             : {"type" : "armor", "attack" : 0, "defense" : 5, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "arms"},
        # Legs
        'pants'                      : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 50, "rarity" : 50, "count" : 2, "slot" : "legs"},
        'cuisse'                     : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "legs"},
        'cuisse +1'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "legs"},
        'cuisse +2'                  : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "legs"},
        'poleyn'                     : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "legs"},
        'poleyn +1'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "legs"},
        'poleyn +2'                  : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "legs"},
        'chausses'                   : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 25, "count" : 2, "slot" : "legs"},
        'chausses +1'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 600, "rarity" : 0, "count" : 2, "slot" : "legs"},
        'chausses +2'                : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 900, "rarity" : 0, "count" : 2, "slot" : "legs"},
        # Hands
        'gloves'                     : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 150, "rarity" : 20, "count" : 2, "slot" : "hands"},
        'gloves +1'                  : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'gloves +2'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 450, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'chain gloves'               : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 150, "rarity" : 20, "count" : 2, "slot" : "hands"},
        'chain gloves +1'            : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'chain gloves +2'            : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 450, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'gauntlets'                  : {"type" : "armor", "attack" : 1, "defense" : 2, "value" : 250, "rarity" : 10, "count" : 2, "slot" : "hands"},
        'gauntlets +1'               : {"type" : "armor", "attack" : 2, "defense" : 3, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'gauntlets +2'               : {"type" : "armor", "attack" : 3, "defense" : 4, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'fanged gauntlets'           : {"type" : "armor", "attack" : 3, "defense" : 3, "value" : 1000, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'fanged gauntlets +1'        : {"type" : "armor", "attack" : 4, "defense" : 4, "value" : 2000, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'fanged gauntlets +2'        : {"type" : "armor", "attack" : 5, "defense" : 5, "value" : 3000, "rarity" : 0, "count" : 2, "slot" : "hands"},
        # Feet
        'boots'                      : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 150, "rarity" : 25, "count" : 2, "slot" : "feet"},
        'boots +1'                   : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'boots +2'                   : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 450, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'chain boots'                : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 200, "rarity" : 10, "count" : 2, "slot" : "feet"},
        'chain boots +1'             : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 400, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'chain boots +2'             : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 600, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'sabatons'                   : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 250, "rarity" : 10, "count" : 2, "slot" : "feet"},
        'sabatons +1'                : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'sabatons +2'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'greaves'                    : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 250, "rarity" : 10, "count" : 2, "slot" : "feet"},
        'greaves +1'                 : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'greaves +2'                 : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'full greaves'               : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 10, "count" : 2, "slot" : "feet"},
        'full greaves +1'            : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 600, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'full greaves +2'            : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 900, "rarity" : 0, "count" : 2, "slot" : "feet"},
    }



crafting = {
        ## Items
        
        # Material
        'iron ingot'                : {"take":{"":1}, "give":{"iron ingot":1}},
        'steel ingot'               : {"take":{"":1}, "give":{"steel ingot":1}},
        'copper ingot'              : {"take":{"":1}, "give":{"copper ingot":1}},
        'bronze ingot'              : {"take":{"":1}, "give":{"bronze ingot":1}},
        'silver ingot'              : {"take":{"":1}, "give":{"silver ingot":1}},
        'gold ingot'                : {"take":{"":1}, "give":{"gold ingot":1}},
        'mythril ingot'             : {"take":{"":1}, "give":{"mythril ingot":1}},
        'iron bar'                  : {"take":{"":1}, "give":{"iron bar":1}},
        'steel bar'                 : {"take":{"":1}, "give":{"steel bar":1}},
        'copper bar'                : {"take":{"":1}, "give":{"copper bar":1}},
        'bronze bar'                : {"take":{"":1}, "give":{"bronze bar":1}},
        'silver bar'                : {"take":{"":1}, "give":{"silver bar":1}},
        'gold bar'                  : {"take":{"":1}, "give":{"gold bar":1}},
        'mythril bar'               : {"take":{"":1}, "give":{"mythril bar":1}},
        'iron rod'                  : {"take":{"":1}, "give":{"iron rod":1}},
        'steel rod'                 : {"take":{"":1}, "give":{"steel rod":1}},
        'copper rod'                : {"take":{"":1}, "give":{"copper rod":1}},
        'bronze rod'                : {"take":{"":1}, "give":{"bronze rod":1}},
        'silver rod'                : {"take":{"":1}, "give":{"silver rod":1}},
        'gold rod'                  : {"take":{"":1}, "give":{"gold rod":1}},
        'mythril rod'               : {"take":{"":1}, "give":{"mythril rod":1}},
        'iron wire'                 : {"take":{"":1}, "give":{"iron wire":1}},
        'steel wire'                : {"take":{"":1}, "give":{"steel wire":1}},
        'copper wire'               : {"take":{"":1}, "give":{"copper wire":1}},
        'bronze wire'               : {"take":{"":1}, "give":{"bronze wire":1}},
        'silver wire'               : {"take":{"":1}, "give":{"silver wire":1}},
        'gold wire'                 : {"take":{"":1}, "give":{"gold wire":1}},
        'mythril wire'              : {"take":{"":1}, "give":{"mythril wire":1}},
        'cloth'                     : {"take":{"":1}, "give":{"cloth":1}},
        'rope'                      : {"take":{"":1}, "give":{"rope":1}},
        'string'                    : {"take":{"":1}, "give":{"string":1}},
        
        ## Arms
        
        # Bludgeon
        'club'                       : {"take":{"":1}, "give":{"club":1}},
        'club +1'                    : {"take":{"":1}, "give":{"club +1":1}},
        'club +2'                    : {"take":{"":1}, "give":{"club 2+":1}},
        'spiked club'                : {"take":{"":1}, "give":{"spiked club":1}},
        'spiked club +1'             : {"take":{"":1}, "give":{"spiked club +1":1}},
        'spiked club +2'             : {"take":{"":1}, "give":{"spiked club +2":1}},
        'mace'                       : {"take":{"":1}, "give":{"mace":1}},
        'mace +1'                    : {"take":{"":1}, "give":{"mace +1":1}},
        'mace +2'                    : {"take":{"":1}, "give":{"mace +2":1}},
        'greatmace'                  : {"take":{"":1}, "give":{"greatmace":1}},
        'greatmace +1'               : {"take":{"":1}, "give":{"greatmace +1":1}},
        'greatmace +2'               : {"take":{"":1}, "give":{"greatmace +2":1}},
        'morning star'               : {"take":{"":1}, "give":{"morning star":1}},
        'morning star +1'            : {"take":{"":1}, "give":{"morning star +1":1}},
        'morning star +2'            : {"take":{"":1}, "give":{"morning star +2":1}},
        'war hammer'                 : {"take":{"":1}, "give":{"war hammer":1}},
        'war hammer +1'              : {"take":{"":1}, "give":{"war hammer +1":1}},
        'war hammer +2'              : {"take":{"":1}, "give":{"war hammer +2":1}},
        # Axe
        'war axe'                    : {"take":{"":1}, "give":{"war axe":1}},
        'war axe +1'                 : {"take":{"":1}, "give":{"war axe +1":1}},
        'war axe +2'                 : {"take":{"":1}, "give":{"war axe +2":1}},
        'great war axe'              : {"take":{"":1}, "give":{"great war axe":1}},
        'great war axe +1'           : {"take":{"":1}, "give":{"great war axe +1":1}},
        'great war axe +2'           : {"take":{"":1}, "give":{"great war axe +2":1}},
        'igorot'                     : {"take":{"":1}, "give":{"igorot":1}},
        'igorot +1'                  : {"take":{"":1}, "give":{"igorot +1":1}},
        'igorot +2'                  : {"take":{"":1}, "give":{"igorot +2":1}},
        'lochaber axe'               : {"take":{"":1}, "give":{"lochaber axe":1}},
        'lochaber axe +1'            : {"take":{"":1}, "give":{"lochaber axe +1":1}},
        'lochaber axe +2'            : {"take":{"":1}, "give":{"lochaber axe +2":1}},
        'bardiche'                   : {"take":{"":1}, "give":{"bardiche":1}},
        'bardiche +1'                : {"take":{"":1}, "give":{"bardiche +1":1}},
        'bardiche +2'                : {"take":{"":1}, "give":{"bardiche +2":1}},
        'halberd'                    : {"take":{"":1}, "give":{"halberd":1}},
        'halberd +1'                 : {"take":{"":1}, "give":{"halberd +1":1}},
        'halberd +2'                 : {"take":{"":1}, "give":{"halberd +2":1}},
        # Dagger
        'dagger'                     : {"take":{"":1}, "give":{"dagger":1}},
        'dagger +1'                  : {"take":{"":1}, "give":{"dagger +1":1}},
        'dagger +2'                  : {"take":{"":1}, "give":{"dagger +2":1}},
        'athame'                     : {"take":{"":1}, "give":{"athame":1}},
        'athame +1'                  : {"take":{"":1}, "give":{"athame +1":1}},
        'athame +2'                  : {"take":{"":1}, "give":{"athame +2":1}},
        'pugio'                      : {"take":{"":1}, "give":{"pugio":1}},
        'pugio +1'                   : {"take":{"":1}, "give":{"pugio +1":1}},
        'pugio +2'                   : {"take":{"":1}, "give":{"pugio +2":1}},
        'cinquedea'                  : {"take":{"":1}, "give":{"cinquedea":1}},
        'cinquedea +1'               : {"take":{"":1}, "give":{"cinquedea +1":1}},
        'cinquedea +2'               : {"take":{"":1}, "give":{"cinquedea +2":1}},
        'dirk'                       : {"take":{"":1}, "give":{"dirk":1}},
        'dirk +1'                    : {"take":{"":1}, "give":{"dirk +1":1}},
        'dirk +2'                    : {"take":{"":1}, "give":{"dirk +2":1}},
        'acinaces'                   : {"take":{"":1}, "give":{"acinaces":1}},
        'acinaces +1'                : {"take":{"":1}, "give":{"acinaces +1":1}},
        'acinaces +2'                : {"take":{"":1}, "give":{"acinaces +2":1}},
        'anelace'                    : {"take":{"":1}, "give":{"anelace":1}},
        'anelace +1'                 : {"take":{"":1}, "give":{"anelace +1":1}},
        'anelace +2'                 : {"take":{"":1}, "give":{"anelace +2":1}},
        # Knife
        'kiridashi'                  : {"take":{"":1}, "give":{"kiridashi":1}},
        'kiridashi +1'               : {"take":{"":1}, "give":{"kiridashi +1":1}},
        'kiridashi +2'               : {"take":{"":1}, "give":{"kiridashi +2":1}},
        'karambit'                   : {"take":{"":1}, "give":{"karambit":1}},
        'karambit +1'                : {"take":{"":1}, "give":{"karambit +1":1}},
        'karambit +2'                : {"take":{"":1}, "give":{"karambit +2":1}},
        'puuko'                      : {"take":{"":1}, "give":{"puuko":1}},
        'puuko +1'                   : {"take":{"":1}, "give":{"puuko +1":1}},
        'puuko +2'                   : {"take":{"":1}, "give":{"puuko +2":1}},
        'sgian dubh'                 : {"take":{"":1}, "give":{"sgian dubh":1}},
        'sgian dubh +1'              : {"take":{"":1}, "give":{"sgian dubh +1":1}},
        'sgian dubh +2'              : {"take":{"":1}, "give":{"sgian dubh +2":1}},
        'tanto'                      : {"take":{"":1}, "give":{"tanto":1}},
        'tanto +1'                   : {"take":{"":1}, "give":{"tanto +1":1}},
        'tanto +2'                   : {"take":{"":1}, "give":{"tanto +2":1}},
        'kirpan'                     : {"take":{"":1}, "give":{"kirpan":1}},
        'kirpan +1'                  : {"take":{"":1}, "give":{"kirpan +1":1}},
        'kirpan +2'                  : {"take":{"":1}, "give":{"kirpan +2":1}},
        'seax'                       : {"take":{"":1}, "give":{"seax":1}},
        'seax +1'                    : {"take":{"":1}, "give":{"seax +1":1}},
        'seax +2'                    : {"take":{"":1}, "give":{"seax +2":1}},
        'kukri'                      : {"take":{"":1}, "give":{"kukri":1}},
        'kukri +1'                   : {"take":{"":1}, "give":{"kukri +1":1}},
        'kukri +2'                   : {"take":{"":1}, "give":{"kukri +2":1}},
        'machete'                    : {"take":{"":1}, "give":{"machete":1}},
        'machete +1'                 : {"take":{"":1}, "give":{"machete +1":1}},
        'machete +2'                 : {"take":{"":1}, "give":{"machete +2":1}},
        # Sword
        'bastardsword'               : {"take":{"":1}, "give":{"bastardsword":1}},
        'bastardsword +1'            : {"take":{"":1}, "give":{"bastardsword +1":1}},
        'bastardsword +2'            : {"take":{"":1}, "give":{"bastardsword +2":1}},
        'shortsword'                 : {"take":{"":1}, "give":{"shortsword":1}},
        'shortsword +1'              : {"take":{"":1}, "give":{"shortsword +1":1}},
        'shortsword +2'              : {"take":{"":1}, "give":{"shortsword +2":1}},
        'longsword'                  : {"take":{"":1}, "give":{"longsword":1}},
        'longsword +1'               : {"take":{"":1}, "give":{"longsword +1":1}},
        'longsword +2'               : {"take":{"":1}, "give":{"longsword +2":1}},
        'rapier'                     : {"take":{"":1}, "give":{"rapier":1}},
        'rapier +1'                  : {"take":{"":1}, "give":{"rapier +1":1}},
        'rapier +2'                  : {"take":{"":1}, "give":{"rapier +2":1}},
        'sabre'                      : {"take":{"":1}, "give":{"sabre":1}},
        'sabre +1'                   : {"take":{"":1}, "give":{"sabre +1":1}},
        'sabre +2'                   : {"take":{"":1}, "give":{"sabre +2":1}},
        'falchion'                   : {"take":{"":1}, "give":{"falchion":1}},
        'falchion +1'                : {"take":{"":1}, "give":{"falchion +1":1}},
        'falchion +2'                : {"take":{"":1}, "give":{"falchion +2":1}},
        'scimitar'                   : {"take":{"":1}, "give":{"scimitar":1}},
        'scimitar +1'                : {"take":{"":1}, "give":{"scimitar +1":1}},
        'scimitar +2'                : {"take":{"":1}, "give":{"scimitar +2":1}},
        'kopesh'                     : {"take":{"":1}, "give":{"kopesh":1}},
        'kopesh +1'                  : {"take":{"":1}, "give":{"kopesh +1":1}},
        'kopesh +2'                  : {"take":{"":1}, "give":{"kopesh +2":1}},
        'kopis'                      : {"take":{"":1}, "give":{"kopis":1}},
        'kopis +1'                   : {"take":{"":1}, "give":{"kopis +1":1}},
        'kopis +2'                   : {"take":{"":1}, "give":{"kopis +2":1}},
        'katana'                     : {"take":{"":1}, "give":{"katana":1}},
        'katana +1'                  : {"take":{"":1}, "give":{"katana +1":1}},
        'katana +2'                  : {"take":{"":1}, "give":{"katana +2":1}},
        # Great Sword
        'uchigatana'                 : {"take":{"":1}, "give":{"uchigatana":1}},
        'uchigatana +1'              : {"take":{"":1}, "give":{"uchigatana +1":1}},
        'uchigatana +2'              : {"take":{"":1}, "give":{"uchigatana +2":1}},
        'greatsword'                 : {"take":{"":1}, "give":{"greatsword":1}},
        'greatsword +1'              : {"take":{"":1}, "give":{"greatsword +1":1}},
        'greatsword +2'              : {"take":{"":1}, "give":{"greatsword +2":1}},
        'claymore'                   : {"take":{"":1}, "give":{"claymore":1}},
        'claymore +1'                : {"take":{"":1}, "give":{"claymore +1":1}},
        'claymore +2'                : {"take":{"":1}, "give":{"claymore +2":1}},
        'flamberge'                  : {"take":{"":1}, "give":{"flamberge":1}},
        'flamberge +1'               : {"take":{"":1}, "give":{"flamberge +1":1}},
        'flamberge +2'               : {"take":{"":1}, "give":{"flamberge +2":1}},
        # Polearm
        'hunting spear'              : {"take":{"":1}, "give":{"hunting spear":1}},
        'hunting spear +1'           : {"take":{"":1}, "give":{"hunting spear +1":1}},
        'hunting spear +2'           : {"take":{"":1}, "give":{"hunting spear +2":1}},
        'spear'                      : {"take":{"":1}, "give":{"spear":1}},
        'spear +1'                   : {"take":{"":1}, "give":{"spear +1":1}},
        'spear +2'                   : {"take":{"":1}, "give":{"spear +2":1}},
        'pike'                       : {"take":{"":1}, "give":{"pike":1}},
        'pike +1'                    : {"take":{"":1}, "give":{"pike +1":1}},
        'pike +2'                    : {"take":{"":1}, "give":{"pike +2":1}},
        'lance'                      : {"take":{"":1}, "give":{"lance":1}},
        'lance +1'                   : {"take":{"":1}, "give":{"lance +1":1}},
        'lance +2'                   : {"take":{"":1}, "give":{"lance +2":1}},
        'voulge'                     : {"take":{"":1}, "give":{"voulge":1}},
        'voulge +1'                  : {"take":{"":1}, "give":{"voulge +1":1}},
        'voulge +2'                  : {"take":{"":1}, "give":{"voulge +2":1}},
        # Shield
        'buckler'                    : {"take":{"":1}, "give":{"buckler":1}},
        'buckler +1'                 : {"take":{"":1}, "give":{"buckler +1":1}},
        'buckler +2'                 : {"take":{"":1}, "give":{"buckler +2":1}},
        'shield'                     : {"take":{"":1}, "give":{"shield":1}},
        'shield +1'                  : {"take":{"":1}, "give":{"shield +1":1}},
        'shield +2'                  : {"take":{"":1}, "give":{"shield +2":1}},
        'tower shield'               : {"take":{"":1}, "give":{"tower shield":1}},
        'tower shield +1'            : {"take":{"":1}, "give":{"tower shield +1":1}},
        'tower shield +2'            : {"take":{"":1}, "give":{"tower shield +2":1}},
        # Ranged
        'flintlock pistol'           : {"take":{"":1}, "give":{"flintlock pistol":1}},
        'flintlock pistol +1'        : {"take":{"":1}, "give":{"flintlock pistol +1":1}},
        'flintlock pistol +2'        : {"take":{"":1}, "give":{"flintlock pistol +2":1}},
        'revolver'                   : {"take":{"":1}, "give":{"revolver":1}},
        'revolver +1'                : {"take":{"":1}, "give":{"revolver +1":1}},
        'revolver +2'                : {"take":{"":1}, "give":{"revolver +2":1}},
        'flintlock rifle'            : {"take":{"":1}, "give":{"flintlock rifle":1}},
        'flintlock rifle +1'         : {"take":{"":1}, "give":{"flintlock rifle +1":1}},
        'flintlock rifle +2'         : {"take":{"":1}, "give":{"flintlock rifle +2":1}},
        'revolver rifle'             : {"take":{"":1}, "give":{"revolver rifle":1}},
        'revolver rifle +1'          : {"take":{"":1}, "give":{"revolver rifle +1":1}},
        'revolver rifle +2'          : {"take":{"":1}, "give":{"revolver rifle +2":1}},
        
        
        
		## Armor
        
        # Necklace
        'necklace'                   : {"take":{"":1}, "give":{"necklace":1}},
        'magic necklace'             : {"take":{"":1}, "give":{"magic necklace":1}},
        'magic necklace +1'          : {"take":{"":1}, "give":{"magic necklace +1":1}},
        'magic necklace +2'          : {"take":{"":1}, "give":{"magic necklace +2":1}},
        'blessed necklace'           : {"take":{"":1}, "give":{"blessed necklace":1}},
        'blessed necklace +1'        : {"take":{"":1}, "give":{"blessed necklace +1":1}},
        'blessed necklace +2'        : {"take":{"":1}, "give":{"blessed necklace +2":1}},
        # Rings
        'ring'                       : {"take":{"":1}, "give":{"ring":1}},
        'magic ring'                 : {"take":{"":1}, "give":{"magic ring":1}},
        'magic ring +1'              : {"take":{"":1}, "give":{"magic ring +1":1}},
        'magic ring +2'              : {"take":{"":1}, "give":{"magic ring +2":1}},
        'blessed ring'               : {"take":{"":1}, "give":{"blessed ring":1}},
        'blessed ring +1'            : {"take":{"":1}, "give":{"blessed ring +1":1}},
        'blessed ring +2'            : {"take":{"":1}, "give":{"blessed ring +2":1}},
        
        # Head
        'coif'                       : {"take":{"":1}, "give":{"coif":1}},
        'coif +1'                    : {"take":{"":1}, "give":{"coif +1":1}},
        'coif +2'                    : {"take":{"":1}, "give":{"coif +2":1}},
        'cervelliere'                : {"take":{"":1}, "give":{"cervelliere":1}},
        'cervelliere +1'             : {"take":{"":1}, "give":{"cervelliere +1":1}},
        'cervelliere +2'             : {"take":{"":1}, "give":{"cervelliere +2":1}},
        'nasal helm'                 : {"take":{"":1}, "give":{"nasal helm":1}},
        'nasal helm +1'              : {"take":{"":1}, "give":{"nasal helm +1":1}},
        'nasal helm +2'              : {"take":{"":1}, "give":{"nasal helm +2":1}},
        'sallet'                     : {"take":{"":1}, "give":{"sallet":1}},
        'sallet +1'                  : {"take":{"":1}, "give":{"sallet +1":1}},
        'sallet +2'                  : {"take":{"":1}, "give":{"sallet +2":1}},
        'barbute'                    : {"take":{"":1}, "give":{"barbute":1}},
        'barbute +1'                 : {"take":{"":1}, "give":{"barbute +1":1}},
        'barbute +2'                 : {"take":{"":1}, "give":{"barbute +2":1}},
        'greathelm'                  : {"take":{"":1}, "give":{"greathelm":1}},
        'greathelm +1'               : {"take":{"":1}, "give":{"greathelm +1":1}},
        'greathelm +2'               : {"take":{"":1}, "give":{"greathelm +2":1}},
        'bassinet'                   : {"take":{"":1}, "give":{"bassinet":1}},
        'bassinet +1'                : {"take":{"":1}, "give":{"bassinet +1":1}},
        'bassinet +2'                : {"take":{"":1}, "give":{"bassinet +2":1}},
        'close helm'                 : {"take":{"":1}, "give":{"close helm":1}},
        'close helm +1'              : {"take":{"":1}, "give":{"close helm +1":1}},
        'close helm +2'              : {"take":{"":1}, "give":{"close helm +2":1}},
        # Neck
        'cloak'                      : {"take":{"":1}, "give":{"cloak":1}},
        'bevor'                      : {"take":{"":1}, "give":{"bevor":1}},
        'bevor +1'                   : {"take":{"":1}, "give":{"bevor +1":1}},
        'bevor +2'                   : {"take":{"":1}, "give":{"bevor +2":1}},
        'gorget'                     : {"take":{"":1}, "give":{"gorget":1}},
        'gorget +1'                  : {"take":{"":1}, "give":{"gorget +1":1}},
        'gorget +2'                  : {"take":{"":1}, "give":{"gorget +2":1}},
        # Shoulders
        'spaulders'                  : {"take":{"":1}, "give":{"spaulders":1}},
        'spaulders +1'               : {"take":{"":1}, "give":{"spaulders +1":1}},
        'spaulders +2'               : {"take":{"":1}, "give":{"spaulders +2":1}},
        'pauldrons'                  : {"take":{"":1}, "give":{"pauldrons":1}},
        'pauldrons +1'               : {"take":{"":1}, "give":{"pauldrons +1":1}},
        'pauldrons +2'               : {"take":{"":1}, "give":{"pauldrons +2":1}},
        # Torso
        'shirt'                      : {"take":{"":1}, "give":{"shirt":1}},
        'ringmail'                   : {"take":{"":1}, "give":{"ringmail":1}},
        'ringmail +1'                : {"take":{"":1}, "give":{"ringmail +1":1}},
        'ringmail +2'                : {"take":{"":1}, "give":{"ringmail +2":1}},
        'hauberk'                    : {"take":{"":1}, "give":{"hauberk":1}},
        'hauberk +1'                 : {"take":{"":1}, "give":{"hauberk +1":1}},
        'hauberk +2'                 : {"take":{"":1}, "give":{"hauberk +2":1}},
        'breastplate'                : {"take":{"":1}, "give":{"breastplate":1}},
        'breastplate +1'             : {"take":{"":1}, "give":{"breastplate +1":1}},
        'breastplate +2'             : {"take":{"":1}, "give":{"breastplate +2":1}},
        'coat of plates'             : {"take":{"":1}, "give":{"coat of plates":1}},
        'coat of plates +1'          : {"take":{"":1}, "give":{"coat of plates +1":1}},
        'coat of plates +2'          : {"take":{"":1}, "give":{"coat of plates +2":1}},
        'cuirass'                    : {"take":{"":1}, "give":{"cuirass":1}},
        'cuirass +1'                 : {"take":{"":1}, "give":{"cuirass +1":1}},
        'cuirass +2'                 : {"take":{"":1}, "give":{"cuirass +2":1}},
        'leather cuirass'            : {"take":{"":1}, "give":{"leather cuirass":1}},
        'leather cuirass +1'         : {"take":{"":1}, "give":{"leather cuirass +1":1}},
        'leather cuirass +2'         : {"take":{"":1}, "give":{"leather cuirass +2":1}},
        'studded leather cuirass'    : {"take":{"":1}, "give":{"studded leather cuirass":1}},
        'studded leather cuirass +1' : {"take":{"":1}, "give":{"studded leather cuirass +1":1}},
        'studded leather cuirass +2' : {"take":{"":1}, "give":{"studded leather cuirass +2":1}},
        # Waist
        'belt'                       : {"take":{"":1}, "give":{"belt":1}},
        'chainskirt'                 : {"take":{"":1}, "give":{"chainskirt":1}},
        'chainskirt +1'              : {"take":{"":1}, "give":{"chainskirt +1":1}},
        'chainskirt +2'              : {"take":{"":1}, "give":{"chainskirt +2":1}},
        'tassets'                    : {"take":{"":1}, "give":{"tassets":1}},
        'tassets +1'                 : {"take":{"":1}, "give":{"tassets +1":1}},
        'tassets +2'                 : {"take":{"":1}, "give":{"tassets +2":1}},
        'fauld'                      : {"take":{"":1}, "give":{"fauld":1}},
        'fauld +1'                   : {"take":{"":1}, "give":{"fauld +1":1}},
        'fauld +2'                   : {"take":{"":1}, "give":{"fauld +2":1}},
        # Arms
        'bracers'                    : {"take":{"":1}, "give":{"bracers":1}},
        'bracers +1'                 : {"take":{"":1}, "give":{"bracers +1":1}},
        'bracers +2'                 : {"take":{"":1}, "give":{"bracers +2":1}},
        'vambrace'                   : {"take":{"":1}, "give":{"vambrace":1}},
        'vambrace +1'                : {"take":{"":1}, "give":{"vambrace +1":1}},
        'vambrace +2'                : {"take":{"":1}, "give":{"vambrace +2":1}},
        'rerebrace'                  : {"take":{"":1}, "give":{"rerebrace":1}},
        'rerebrace +1'               : {"take":{"":1}, "give":{"rerebrace +1":1}},
        'rerebrace +2'               : {"take":{"":1}, "give":{"rerebrace +2":1}},
        'full cannon'                : {"take":{"":1}, "give":{"full cannon":1}},
        'full cannon +1'             : {"take":{"":1}, "give":{"full cannon +1":1}},
        'full cannon +2'             : {"take":{"":1}, "give":{"full cannon +2":1}},
        # Legs
        'pants'                      : {"take":{"":1}, "give":{"pants":1}},
        'cuisse'                     : {"take":{"":1}, "give":{"cuisse":1}},
        'cuisse +1'                  : {"take":{"":1}, "give":{"cuisse +1":1}},
        'cuisse +2'                  : {"take":{"":1}, "give":{"cuisse +2":1}},
        'poleyn'                     : {"take":{"":1}, "give":{"poleyn":1}},
        'poleyn +1'                  : {"take":{"":1}, "give":{"poleyn +1":1}},
        'poleyn +2'                  : {"take":{"":1}, "give":{"poleyn +2":1}},
        'chausses'                   : {"take":{"":1}, "give":{"chausses":1}},
        'chausses +1'                : {"take":{"":1}, "give":{"chausses +1":1}},
        'chausses +2'                : {"take":{"":1}, "give":{"chausses +2":1}},
        # Hands
        'gloves'                     : {"take":{"":1}, "give":{"gloves":1}},
        'gloves +1'                  : {"take":{"":1}, "give":{"gloves +1":1}},
        'gloves +2'                  : {"take":{"":1}, "give":{"gloves +2":1}},
        'chain gloves'               : {"take":{"":1}, "give":{"chain gloves":1}},
        'chain gloves +1'            : {"take":{"":1}, "give":{"chain gloves +1":1}},
        'chain gloves +2'            : {"take":{"":1}, "give":{"chain gloves +2":1}},
        'gauntlets'                  : {"take":{"":1}, "give":{"gauntlets":1}},
        'gauntlets +1'               : {"take":{"":1}, "give":{"gauntlets +1":1}},
        'gauntlets +2'               : {"take":{"":1}, "give":{"gauntlets +2":1}},
        'fanged gauntlets'           : {"take":{"":1}, "give":{"fanged gauntlets":1}},
        'fanged gauntlets +1'        : {"take":{"":1}, "give":{"fanged gauntlets +1":1}},
        'fanged gauntlets +2'        : {"take":{"":1}, "give":{"fanged gauntlets +2":1}},
        # Feet
        'boots'                      : {"take":{"":1}, "give":{"boots":1}},
        'boots +1'                   : {"take":{"":1}, "give":{"boots +1":1}},
        'boots +2'                   : {"take":{"":1}, "give":{"boots +2":1}},
        'chain boots'                : {"take":{"":1}, "give":{"chain boots":1}},
        'chain boots +1'             : {"take":{"":1}, "give":{"chain boots +1":1}},
        'chain boots +2'             : {"take":{"":1}, "give":{"chain boots +2":1}},
        'sabatons'                   : {"take":{"":1}, "give":{"sabatons":1}},
        'sabatons +1'                : {"take":{"":1}, "give":{"sabatons +1":1}},
        'sabatons +2'                : {"take":{"":1}, "give":{"sabatons +2":1}},
        'greaves'                    : {"take":{"":1}, "give":{"greaves":1}},
        'greaves +1'                 : {"take":{"":1}, "give":{"greaves +1":1}},
        'greaves +2'                 : {"take":{"":1}, "give":{"greaves +2":1}},
        'full greaves'               : {"take":{"":1}, "give":{"full greaves":1}},
        'full greaves +1'            : {"take":{"":1}, "give":{"full greaves +1":1}},
        'full greaves +2'            : {"take":{"":1}, "give":{"full greaves +2":1}},
    }
