items = {
        ## None
        'nothing'                   : {"type" : "", "attack" : 0, "defense" : 0, "value" : 0, "rarity" : 0, "count" : 0},
        
        ## Consumable

        # Material
        'iron ingot'                : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'steel ingot'               : {"type" : "material", "value" : 125, "rarity" : 0, "count" : 1},
        'copper ingot'              : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'bronze ingot'              : {"type" : "material", "value" : 125, "rarity" : 0, "count" : 1},
        'silver ingot'              : {"type" : "material", "value" : 250, "rarity" : 0, "count" : 1},
        'gold ingot'                : {"type" : "material", "value" : 1250, "rarity" : 0, "count" : 1},
        'mythril ingot'             : {"type" : "material", "value" : 5000, "rarity" : 0, "count" : 1},
        'iron bar'                  : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'steel bar'                 : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'copper bar'                : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'bronze bar'                : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'silver bar'                : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'gold bar'                  : {"type" : "material", "value" : 250, "rarity" : 0, "count" : 1},
        'mythril bar'               : {"type" : "material", "value" : 1000, "rarity" : 0, "count" : 1},
        'iron plate'                : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1},
        'steel plate'               : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'copper plate'              : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1},
        'bronze plate'              : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'silver plate'              : {"type" : "material", "value" : 100, "rarity" : 0, "count" : 1},
        'gold plate'                : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1},
        'mythril plate'             : {"type" : "material", "value" : 2000, "rarity" : 0, "count" : 1},
        'iron rod'                  : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1},
        'steel rod'                 : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'copper rod'                : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1},
        'bronze rod'                : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'silver rod'                : {"type" : "material", "value" : 100, "rarity" : 0, "count" : 1},
        'gold rod'                  : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1},
        'mythril rod'               : {"type" : "material", "value" : 2000, "rarity" : 0, "count" : 1},
        'spool of iron wire'        : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'spool of steel wire'       : {"type" : "material", "value" : 250, "rarity" : 0, "count" : 1},
        'spool of copper wire'      : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'spool of bronze wire'      : {"type" : "material", "value" : 250, "rarity" : 0, "count" : 1},
        'spool of silver wire'      : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1},
        'spool of gold wire'        : {"type" : "material", "value" : 2500, "rarity" : 0, "count" : 1},
        'spool of mythril wire'     : {"type" : "material", "value" : 10000, "rarity" : 0, "count" : 1},
        'iron wire'                 : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1},
        'steel wire'                : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'copper wire'               : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1},
        'bronze wire'               : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'silver wire'               : {"type" : "material", "value" : 100, "rarity" : 0, "count" : 1},
        'gold wire'                 : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1},
        'mythril wire'              : {"type" : "material", "value" : 2000, "rarity" : 0, "count" : 1},
        'iron ring'                 : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1,},
        'steel ring'                : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1,},
        'copper ring'               : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1,},
        'bronze ring'               : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1,},
        'silver ring'               : {"type" : "material", "value" : 100, "rarity" : 0, "count" : 1,},
        'gold ring'                 : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1,},
        'mythril ring'              : {"type" : "material", "value" : 2000, "rarity" : 0, "count" : 1,},
        'iron jump rings'           : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1,},
        'steel jump rings'          : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1,},
        'copper jump rings'         : {"type" : "material", "value" : 10, "rarity" : 0, "count" : 1,},
        'bronze jump rings'         : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1,},
        'silver jump rings'         : {"type" : "material", "value" : 100, "rarity" : 0, "count" : 1,},
        'gold jump rings'           : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1,},
        'mythril jump rings'        : {"type" : "material", "value" : 2000, "rarity" : 0, "count" : 1,},
        'wood'                      : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'ent wood'                  : {"type" : "material", "value" : 250, "rarity" : 0, "count" : 1},
        'cloth'                     : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'rope'                      : {"type" : "material", "value" : 25, "rarity" : 0, "count" : 1},
        'string'                    : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'leather'                   : {"type" : "material", "value" : 50, "rarity" : 0, "count" : 1},
        'wyvern hide'               : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1},
        'dragon hide'               : {"type" : "material", "value" : 1000, "rarity" : 0, "count" : 1},
        'gargoyle fang'             : {"type" : "material", "value" : 100, "rarity" : 0, "count" : 1},
        'wyvern fang'               : {"type" : "material", "value" : 250, "rarity" : 0, "count" : 1},
        'dragon fang'               : {"type" : "material", "value" : 500, "rarity" : 0, "count" : 1},
        'raw meat'                  : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'raw fish'                  : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},
        'flax'                      : {"type" : "material", "value" : 5, "rarity" : 0, "count" : 1},

        # Food
        'porridge'                  : {"type" : "food", "hp" : 5, "mp" : 5, "value" : 25, "rarity" : 150, "count" : 2},
        'haggis'                    : {"type" : "food", "hp" : 15, "mp" : 15, "value" : 50, "rarity" : 50, "count" : 5},
        'bread'                     : {"type" : "food", "hp" : 5, "mp" : 5, "value" : 25, "rarity" : 150, "count" : 2},
		'kebab'                     : {"type" : "food", "hp" : 10, "mp" : 10, "value" : 50, "rarity" : 50, "count" : 5},
        'fish'                      : {"type" : "food", "hp" : 10, "mp" : 10, "value" : 25, "rarity" : 50, "count" : 5},
        'steak'                     : {"type" : "food", "hp" : 15, "mp" : 15, "value" : 50, "rarity" : 50, "count" : 5},
        'soup'                      : {"type" : "food", "hp" : 10, "mp" : 10, "value" : 25, "rarity" : 100, "count" : 4},
        'stew'                      : {"type" : "food", "hp" : 15, "mp" : 15, "value" : 25, "rarity" : 100, "count" : 4},

        # Potion
        'minor health potion'       : {"type" : "potion", "hp" : 10, "value" : 500, "rarity" : 250, "count" : 10},
        'health potion'             : {"type" : "potion", "hp" : 25, "value" : 250, "rarity" : 100, "count" : 5},
        'major health potion'       : {"type" : "potion", "hp" : 50, "value" : 100, "rarity" : 50, "count" : 2},
        'minor mana potion'         : {"type" : "potion", "mp" : 10, "value" : 500, "rarity" : 250, "count" : 10},
        'mana potion'               : {"type" : "potion", "mp" : 25, "value" : 250, "rarity" : 100, "count" : 5},
        'major mana potion'         : {"type" : "potion", "mp" : 50, "value" : 100, "rarity" : 50, "count" : 2},
        'elixer'                    : {"type" : "potion", "hp" : 25, "mp" : 25, "value" : 250, "rarity" : 100, "count" : 5},
        'restoration potion'        : {"type" : "potion", "hp" : 10000000, "mp" : 10000000, "value" : 1000, "rarity" : 50, "count" : 2},
        'potion of blessings'       : {"type" : "potion", "mag" : 1, "atk" : 1, "def" : 1, "value" : 50000, "rarity" : 1, "count" : 2},
        'potion of magic'           : {"type" : "potion", "mag" : 1, "value" : 25000, "rarity" : 2, "count" : 2},
        'potion of attack'          : {"type" : "potion", "atk" : 1, "value" : 25000, "rarity" : 2, "count" : 2},
        'potion of defense'         : {"type" : "potion", "def" : 1, "value" : 25000, "rarity" : 2, "count" : 2},
        'potion of health'          : {"type" : "potion", "HP" : 1, "value" : 25000, "rarity" : 5, "count" : 2},
        'potion of mana'            : {"type" : "potion", "MP" : 1, "value" : 25000, "rarity" : 5, "count" : 2},

        # Scroll
        #
        'scroll of firestorm'         : {"type" : "scroll", "spell" : "firestorm", "value" : 5000, "rarity" : 5, "count" : 2},
        'scroll of lightning barrage' : {"type" : "scroll", "spell" : "lightning barrage", "value" : 5000, "rarity" : 5, "count" : 2},
        'scroll of tsunami'           : {"type" : "scroll", "spell" : "tsunami", "value" : 5000, "rarity" : 5, "count" : 2},
        'scroll of earthquake'        : {"type" : "scroll", "spell" : "earthquake", "value" : 5000, "rarity" : 5, "count" : 2},
        'scroll of destroy'           : {"type" : "scroll", "spell" : "destroy", "value" : 5000, "rarity" : 5, "count" : 2},
        #
        'scroll of fireblast'         : {"type" : "scroll", "spell" : "fireblast", "value" : 2500, "rarity" : 10, "count" : 2},
        'scroll of lightning'         : {"type" : "scroll", "spell" : "lightning", "value" : 2500, "rarity" : 10, "count" : 2},
        'scroll of flash flood'       : {"type" : "scroll", "spell" : "flash flood", "value" : 2500, "rarity" : 10, "count" : 2},
        'scroll of fissure'           : {"type" : "scroll", "spell" : "fissure", "value" : 2500, "rarity" : 10, "count" : 2},
        'scroll of kill'              : {"type" : "scroll", "spell" : "kill", "value" : 2500, "rarity" : 10, "count" : 2},
        #
        'scroll of fireball'          : {"type" : "scroll", "spell" : "fireball", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of lightning bolt'    : {"type" : "scroll", "spell" : "lightning bolt", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of water burst'       : {"type" : "scroll", "spell" : "water burst", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of ground collapse'   : {"type" : "scroll", "spell" : "ground collapse", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of harm'              : {"type" : "scroll", "spell" : "harm", "value" : 1000, "rarity" : 25, "count" : 2},
        #
        'scroll of burn'              : {"type" : "scroll", "spell" : "burn", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of electric shock'    : {"type" : "scroll", "spell" : "electric shock", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of poison rain'       : {"type" : "scroll", "spell" : "poison rain", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of tremor'            : {"type" : "scroll", "spell" : "tremor", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of decay'             : {"type" : "scroll", "spell" : "decay", "value" : 1000, "rarity" : 25, "count" : 2},
        #
        'scroll of heal'              : {"type" : "scroll", "spell" : "heal", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of heal all'          : {"type" : "scroll", "spell" : "heal all", "value" : 2500, "rarity" : 5, "count" : 2},
        'scroll of cure'              : {"type" : "scroll", "spell" : "cure", "value" : 2500, "rarity" : 10, "count" : 2},
        'scroll of cure all'          : {"type" : "scroll", "spell" : "cure all", "value" : 5000, "rarity" : 5, "count" : 2},
        'scroll of cure poison'       : {"type" : "scroll", "spell" : "cure poison", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of cure confusion'    : {"type" : "scroll", "spell" : "cure confusion", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of cure stun'         : {"type" : "scroll", "spell" : "cure stun", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of cure burn'         : {"type" : "scroll", "spell" : "cure burn", "value" : 1000, "rarity" : 25, "count" : 2},
        #
        'scroll of inflict poison'    : {"type" : "scroll", "spell" : "inflict poison", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of inflict confusion' : {"type" : "scroll", "spell" : "inflict confusion", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of inflict stun'      : {"type" : "scroll", "spell" : "inflict stun", "value" : 1000, "rarity" : 25, "count" : 2},
        'scroll of inflict burn'      : {"type" : "scroll", "spell" : "inflict burn", "value" : 1000, "rarity" : 25, "count" : 2},
        
        ## Arms
        
        # Bludgeon
        'club'                       : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'club +1'                    : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'club +2'                    : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'spiked club'                : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 100, "rarity" : 200, "count" : 2, "slot" : " hand"},
        'spiked club +1'             : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 100, "rarity" : 200, "count" : 2, "slot" : " hand"},
        'spiked club +2'             : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 100, "rarity" : 200, "count" : 2, "slot" : " hand"},
        'mace'                       : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'mace +1'                    : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 250, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'mace +2'                    : {"type" : "arms", "attack" : 5, "defense" : 0, "value" : 250, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'greatmace'                  : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'greatmace +1'               : {"type" : "arms", "attack" : 6, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'greatmace +2'               : {"type" : "arms", "attack" : 7, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'morning star'               : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'morning star +1'            : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 750, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'morning star +2'            : {"type" : "arms", "attack" : 6, "defense" : 1, "value" : 750, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'war hammer'                 : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'war hammer +1'              : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'war hammer +2'              : {"type" : "arms", "attack" : 6, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        # Axe
        'war axe'                    : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'war axe +1'                 : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'war axe +2'                 : {"type" : "arms", "attack" : 6, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'great war axe'              : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'great war axe +1'           : {"type" : "arms", "attack" : 6, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'great war axe +2'           : {"type" : "arms", "attack" : 7, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'igorot'                     : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'igorot +1'                  : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'igorot +2'                  : {"type" : "arms", "attack" : 6, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'lochaber axe'               : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'lochaber axe +1'            : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'lochaber axe +2'            : {"type" : "arms", "attack" : 6, "defense" : 1, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'bardiche'                   : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'bardiche +1'                : {"type" : "arms", "attack" : 6, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'bardiche +2'                : {"type" : "arms", "attack" : 7, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'halberd'                    : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'halberd +1'                 : {"type" : "arms", "attack" : 6, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'halberd +2'                 : {"type" : "arms", "attack" : 7, "defense" : 2, "value" : 1000, "rarity" : 100, "count" : 2, "slot" : " hand"},
        # Dagger
        'dagger'                     : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'dagger +1'                  : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'dagger +2'                  : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'athame'                     : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'athame +1'                  : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'athame +2'                  : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pugio'                      : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pugio +1'                   : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pugio +2'                   : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'cinquedea'                  : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'cinquedea +1'               : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'cinquedea +2'               : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'dirk'                       : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'dirk +1'                    : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'dirk +2'                    : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'acinaces'                   : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'acinaces +1'                : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'acinaces +2'                : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'anelace'                    : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'anelace +1'                 : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'anelace +2'                 : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        # Knife
        'kiridashi'                  : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kiridashi +1'               : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kiridashi +2'               : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'karambit'                   : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'karambit +1'                : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'karambit +2'                : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'puuko'                      : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'puuko +1'                   : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'puuko +2'                   : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'sgian dubh'                 : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'sgian dubh +1'              : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'sgian dubh +2'              : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'tanto'                      : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'tanto +1'                   : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'tanto +2'                   : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kirpan'                     : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kirpan +1'                  : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kirpan +2'                  : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'seax'                       : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'seax +1'                    : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'seax +2'                    : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kukri'                      : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kukri +1'                   : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'kukri +2'                   : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'machete'                    : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'machete +1'                 : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'machete +2'                 : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 250, "rarity" : 250, "count" : 2, "slot" : " hand"},
        # Sword
        'bastardsword'               : {"type" : "arms", "attack" : 3, "defense" : 2, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'bastardsword +1'            : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'bastardsword +2'            : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'shortsword'                 : {"type" : "arms", "attack" : 2, "defense" : 1, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'shortsword +1'              : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'shortsword +2'              : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 500, "rarity" : 150, "count" : 2, "slot" : " hand"},
        'longsword'                  : {"type" : "arms", "attack" : 3, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'longsword +1'               : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'longsword +2'               : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'rapier'                     : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'rapier +1'                  : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'rapier +2'                  : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'sabre'                      : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'sabre +1'                   : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'sabre +2'                   : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'falchion'                   : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'falchion +1'                : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'falchion +2'                : {"type" : "arms", "attack" : 6, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'scimitar'                   : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'scimitar +1'                : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'scimitar +2'                : {"type" : "arms", "attack" : 6, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopesh'                     : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopesh +1'                  : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopesh +2'                  : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopis'                      : {"type" : "arms", "attack" : 3, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopis +1'                   : {"type" : "arms", "attack" : 4, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'kopis +2'                   : {"type" : "arms", "attack" : 5, "defense" : 1, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'katana'                     : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'katana +1'                  : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'katana +2'                  : {"type" : "arms", "attack" : 6, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        # Great Sword
        'uchigatana'                 : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'uchigatana +1'              : {"type" : "arms", "attack" : 6, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'uchigatana +2'              : {"type" : "arms", "attack" : 7, "defense" : 2, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'greatsword'                 : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'greatsword +1'              : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'greatsword +2'              : {"type" : "arms", "attack" : 6, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'claymore'                   : {"type" : "arms", "attack" : 4, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'claymore +1'                : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'claymore +2'                : {"type" : "arms", "attack" : 6, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'flamberge'                  : {"type" : "arms", "attack" : 5, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'flamberge +1'               : {"type" : "arms", "attack" : 6, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'flamberge +2'               : {"type" : "arms", "attack" : 7, "defense" : 2, "value" : 1000, "rarity" : 50, "count" : 2, "slot" : " hand"},
        # Polearm
        'hunting spear'              : {"type" : "arms", "attack" : 1, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'hunting spear +1'           : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'hunting spear +2'           : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'spear'                      : {"type" : "arms", "attack" : 2, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'spear +1'                   : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'spear +2'                   : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pike'                       : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pike +1'                    : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'pike +2'                    : {"type" : "arms", "attack" : 5, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'lance'                      : {"type" : "arms", "attack" : 3, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'lance +1'                   : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'lance +2'                   : {"type" : "arms", "attack" : 5, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'voulge'                     : {"type" : "arms", "attack" : 4, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'voulge +1'                  : {"type" : "arms", "attack" : 5, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        'voulge +2'                  : {"type" : "arms", "attack" : 6, "defense" : 0, "value" : 50, "rarity" : 250, "count" : 2, "slot" : " hand"},
        # Shield
        'buckler'                    : {"type" : "arms", "attack" : 1, "defense" : 1, "value" : 50, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'buckler +1'                 : {"type" : "arms", "attack" : 1, "defense" : 2, "value" : 50, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'buckler +2'                 : {"type" : "arms", "attack" : 2, "defense" : 3, "value" : 50, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'shield'                     : {"type" : "arms", "attack" : 1, "defense" : 2, "value" : 100, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'shield +1'                  : {"type" : "arms", "attack" : 1, "defense" : 3, "value" : 100, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'shield +2'                  : {"type" : "arms", "attack" : 2, "defense" : 4, "value" : 100, "rarity" : 50, "count" : 2, "slot" : " hand"},
        'tower shield'               : {"type" : "arms", "attack" : 1, "defense" : 4, "value" : 250, "rarity" : 25, "count" : 2, "slot" : " hand"},
        'tower shield +1'            : {"type" : "arms", "attack" : 1, "defense" : 5, "value" : 250, "rarity" : 25, "count" : 2, "slot" : " hand"},
        'tower shield +2'            : {"type" : "arms", "attack" : 2, "defense" : 6, "value" : 250, "rarity" : 25, "count" : 2, "slot" : " hand"},
        # Ranged
        'flintlock pistol'           : {"type" : "arms", "attack" : 6, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'flintlock pistol +1'        : {"type" : "arms", "attack" : 7, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'flintlock pistol +2'        : {"type" : "arms", "attack" : 8, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver'                   : {"type" : "arms", "attack" : 6, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver +1'                : {"type" : "arms", "attack" : 7, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver +2'                : {"type" : "arms", "attack" : 8, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'flintlock rifle'            : {"type" : "arms", "attack" : 8, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'flintlock rifle +1'         : {"type" : "arms", "attack" : 9, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'flintlock rifle +2'         : {"type" : "arms", "attack" : 10, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver rifle'             : {"type" : "arms", "attack" : 8, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver rifle +1'          : {"type" : "arms", "attack" : 9, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        'revolver rifle +2'          : {"type" : "arms", "attack" : 10, "defense" : 0, "value" : 750, "rarity" : 100, "count" : 2, "slot" : " hand"},
        
        ## Armor
        
        # Necklace
        'necklace'                   : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 500, "rarity" : 5, "count" : 2, "slot" : "neck"},
        'magic necklace'             : {"type" : "armor", "magic" : 1, "attack" : 0, "defense" : 0, "value" : 2500, "rarity" : 2, "count" : 2, "slot" : "neck"},
        'magic necklace +1'          : {"type" : "armor", "magic" : 2, "attack" : 0, "defense" : 0, "value" : 5000, "rarity" : 2, "count" : 2, "slot" : "neck"},
        'magic necklace +2'          : {"type" : "armor", "magic" : 3, "attack" : 0, "defense" : 0, "value" : 7500, "rarity" : 2, "count" : 2, "slot" : "neck"},
        'blessed necklace'           : {"type" : "armor", "magic" : 1, "attack" : 1, "defense" : 1, "value" : 2500, "rarity" : 1, "count" : 2, "slot" : "neck"},
        'blessed necklace +1'        : {"type" : "armor", "magic" : 2, "attack" : 2, "defense" : 2, "value" : 5000, "rarity" : 1, "count" : 2, "slot" : "neck"},
        'blessed necklace +2'        : {"type" : "armor", "magic" : 3, "attack" : 3, "defense" : 3, "value" : 7500, "rarity" : 1, "count" : 2, "slot" : "neck"},
        # Rings
        'ring'                       : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 500, "rarity" : 5, "count" : 2, "slot" : "ring"},
        'magic ring'                 : {"type" : "armor", "magic" : 1, "attack" : 0, "defense" : 0, "value" : 2500, "rarity" : 2, "count" : 2, "slot" : "ring"},
        'magic ring +1'              : {"type" : "armor", "magic" : 2, "attack" : 0, "defense" : 0, "value" : 5000, "rarity" : 2, "count" : 2, "slot" : "ring"},
        'magic ring +2'              : {"type" : "armor", "magic" : 3, "attack" : 0, "defense" : 0, "value" : 7500, "rarity" : 2, "count" : 2, "slot" : "ring"},
        'blessed ring'               : {"type" : "armor", "magic" : 1, "attack" : 1, "defense" : 1, "value" : 2500, "rarity" : 1, "count" : 2, "slot" : "ring"},
        'blessed ring +1'            : {"type" : "armor", "magic" : 2, "attack" : 2, "defense" : 2, "value" : 5000, "rarity" : 1, "count" : 2, "slot" : "ring"},
        'blessed ring +2'            : {"type" : "armor", "magic" : 3, "attack" : 3, "defense" : 3, "value" : 7500, "rarity" : 1, "count" : 2, "slot" : "ring"},
        # Head
        'coif'                       : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 200, "rarity" : 15, "count" : 2, "slot" : "head"},
        'coif +1'                    : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 400, "rarity" : 0, "count" : 2, "slot" : "head"},
        'coif +2'                    : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 600, "rarity" : 0, "count" : 2, "slot" : "head"},
        'cervelliere'                : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 150, "rarity" : 15, "count" : 2, "slot" : "head"},
        'cervelliere +1'             : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "head"},
        'cervelliere +2'             : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 450, "rarity" : 0, "count" : 2, "slot" : "head"},
        'nasal helm'                 : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 150, "rarity" : 15, "count" : 2, "slot" : "head"},
        'nasal helm +1'              : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "head"},
        'nasal helm +2'              : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 450, "rarity" : 0, "count" : 2, "slot" : "head"},
        'sallet'                     : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 200, "rarity" : 15, "count" : 2, "slot" : "head"},
        'sallet +1'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 400, "rarity" : 0, "count" : 2, "slot" : "head"},
        'sallet +2'                  : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 600, "rarity" : 0, "count" : 2, "slot" : "head"},
        'barbute'                    : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 250, "rarity" : 15, "count" : 2, "slot" : "head"},
        'barbute +1'                 : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "head"},
        'barbute +2'                 : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "head"},
        'greathelm'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 250, "rarity" : 10, "count" : 2, "slot" : "head"},
        'greathelm +1'               : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "head"},
        'greathelm +2'               : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "head"},
        'bassinet'                   : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 250, "rarity" : 15, "count" : 2, "slot" : "head"},
        'bassinet +1'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "head"},
        'bassinet +2'                : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "head"},
        'close helm'                 : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 250, "rarity" : 15, "count" : 2, "slot" : "head"},
        'close helm +1'              : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "head"},
        'close helm +2'              : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "head"},
        # Neck
        'cloak'                      : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 100, "rarity" : 25, "count" : 3, "slot" : "neck"},
        'bevor'                      : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 250, "rarity" : 10, "count" : 3, "slot" : "neck"},
        'bevor +1'                   : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 0, "count" : 3, "slot" : "neck"},
        'bevor +2'                   : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 0, "count" : 3, "slot" : "neck"},
        'gorget'                     : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 250, "rarity" : 10, "count" : 3, "slot" : "neck"},
        'gorget +1'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 0, "count" : 3, "slot" : "neck"},
        'gorget +2'                  : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 0, "count" : 3, "slot" : "neck"},
        # Shoulders
        'spaulders'                  : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 3, "slot" : "shoulders"},
        'spaulders +1'               : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 3, "slot" : "shoulders"},
        'spaulders +2'               : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 3, "slot" : "shoulders"},
        'pauldrons'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 100, "rarity" : 25, "count" : 3, "slot" : "shoulders"},
        'pauldrons +1'               : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 200, "rarity" : 0, "count" : 3, "slot" : "shoulders"},
        'pauldrons +2'               : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 300, "rarity" : 0, "count" : 3, "slot" : "shoulders"},
        # Torso
        'shirt'                      : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 25, "rarity" : 75, "count" : 2, "slot" : "torso"},
        'ringmail'                   : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 15, "count" : 2, "slot" : "torso"},
        'ringmail +1'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 1000, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'ringmail +2'                : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'scalemail'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 15, "count" : 2, "slot" : "torso"},
        'scalemail +1'               : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 1000, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'scalemail +2'               : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'hauberk'                    : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 10, "count" : 2, "slot" : "torso"},
        'hauberk +1'                 : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'hauberk +2'                 : {"type" : "armor", "attack" : 0, "defense" : 5, "value" : 2250, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'breastplate'                : {"type" : "armor", "attack" : 0, "defense" : 5, "value" : 1000, "rarity" : 5, "count" : 2, "slot" : "torso"},
        'breastplate +1'             : {"type" : "armor", "attack" : 0, "defense" : 6, "value" : 2000, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'breastplate +2'             : {"type" : "armor", "attack" : 0, "defense" : 7, "value" : 3000, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'coat of plates'             : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 5, "count" : 2, "slot" : "torso"},
        'coat of plates +1'          : {"type" : "armor", "attack" : 0, "defense" : 5, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'coat of plates +2'          : {"type" : "armor", "attack" : 0, "defense" : 6, "value" : 2250, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'cuirass'                    : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 750, "rarity" : 5, "count" : 2, "slot" : "torso"},
        'cuirass +1'                 : {"type" : "armor", "attack" : 0, "defense" : 5, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'cuirass +2'                 : {"type" : "armor", "attack" : 0, "defense" : 6, "value" : 2250, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'leather cuirass'            : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 5, "count" : 2, "slot" : "torso"},
        'leather cuirass +1'         : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 1000, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'leather cuirass +2'         : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'studded leather cuirass'    : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 5, "count" : 2, "slot" : "torso"},
        'studded leather cuirass +1' : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 1500, "rarity" : 0, "count" : 2, "slot" : "torso"},
        'studded leather cuirass +2' : {"type" : "armor", "attack" : 0, "defense" : 5, "value" : 2250, "rarity" : 0, "count" : 2, "slot" : "torso"},
        # Waist
        'belt'                       : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 50, "rarity" : 100, "count" : 2, "slot" : "waist"},
        'chainskirt'                 : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 50, "count" : 2, "slot" : "waist"},
        'chainskirt +1'              : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "waist"},
        'chainskirt +2'              : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "waist"},
        'tassets'                    : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 50, "count" : 2, "slot" : "waist"},
        'tassets +1'                 : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "waist"},
        'tassets +2'                 : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "waist"},
        'fauld'                      : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "waist"},
        'fauld +1'                   : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "waist"},
        'fauld +2'                   : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "waist"},
        # Arms
        'bracers'                    : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "arms"},
        'bracers +1'                 : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'bracers +2'                 : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'vambrace'                   : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "arms"},
        'vambrace +1'                : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'vambrace +2'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'rerebrace'                  : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "arms"},
        'rerebrace +1'               : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'rerebrace +2'               : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'full cannon'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 250, "rarity" : 25, "count" : 2, "slot" : "arms"},
        'full cannon +1'             : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "arms"},
        'full cannon +2'             : {"type" : "armor", "attack" : 0, "defense" : 5, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "arms"},
        # Legs
        'pants'                      : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 50, "rarity" : 50, "count" : 2, "slot" : "legs"},
        'cuisse'                     : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "legs"},
        'cuisse +1'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "legs"},
        'cuisse +2'                  : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "legs"},
        'poleyn'                     : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 100, "rarity" : 25, "count" : 2, "slot" : "legs"},
        'poleyn +1'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 200, "rarity" : 0, "count" : 2, "slot" : "legs"},
        'poleyn +2'                  : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "legs"},
        'chausses'                   : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 25, "count" : 2, "slot" : "legs"},
        'chausses +1'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 600, "rarity" : 0, "count" : 2, "slot" : "legs"},
        'chausses +2'                : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 900, "rarity" : 0, "count" : 2, "slot" : "legs"},
        # Hands
        'gloves'                     : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 150, "rarity" : 20, "count" : 2, "slot" : "hands"},
        'gloves +1'                  : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'gloves +2'                  : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 450, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'chain gloves'               : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 150, "rarity" : 20, "count" : 2, "slot" : "hands"},
        'chain gloves +1'            : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'chain gloves +2'            : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 450, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'gauntlets'                  : {"type" : "armor", "attack" : 1, "defense" : 2, "value" : 250, "rarity" : 10, "count" : 2, "slot" : "hands"},
        'gauntlets +1'               : {"type" : "armor", "attack" : 2, "defense" : 3, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'gauntlets +2'               : {"type" : "armor", "attack" : 3, "defense" : 4, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'fanged gauntlets'           : {"type" : "armor", "attack" : 3, "defense" : 3, "value" : 1000, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'fanged gauntlets +1'        : {"type" : "armor", "attack" : 4, "defense" : 4, "value" : 2000, "rarity" : 0, "count" : 2, "slot" : "hands"},
        'fanged gauntlets +2'        : {"type" : "armor", "attack" : 5, "defense" : 5, "value" : 3000, "rarity" : 0, "count" : 2, "slot" : "hands"},
        # Feet
        'boots'                      : {"type" : "armor", "attack" : 0, "defense" : 0, "value" : 150, "rarity" : 25, "count" : 2, "slot" : "feet"},
        'boots +1'                   : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 300, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'boots +2'                   : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 450, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'chain boots'                : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 200, "rarity" : 10, "count" : 2, "slot" : "feet"},
        'chain boots +1'             : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 400, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'chain boots +2'             : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 600, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'sabatons'                   : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 250, "rarity" : 10, "count" : 2, "slot" : "feet"},
        'sabatons +1'                : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'sabatons +2'                : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'greaves'                    : {"type" : "armor", "attack" : 0, "defense" : 1, "value" : 250, "rarity" : 10, "count" : 2, "slot" : "feet"},
        'greaves +1'                 : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 500, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'greaves +2'                 : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 750, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'full greaves'               : {"type" : "armor", "attack" : 0, "defense" : 2, "value" : 300, "rarity" : 10, "count" : 2, "slot" : "feet"},
        'full greaves +1'            : {"type" : "armor", "attack" : 0, "defense" : 3, "value" : 600, "rarity" : 0, "count" : 2, "slot" : "feet"},
        'full greaves +2'            : {"type" : "armor", "attack" : 0, "defense" : 4, "value" : 900, "rarity" : 0, "count" : 2, "slot" : "feet"},
    }



crafting = {
        ## Items
        
        # Material
        'iron ingot'                : {"craft":15, "take":{"iron bar":5}, "give":{"iron ingot":1}},
        'steel ingot'               : {"craft":20, "take":{"steel bar":5}, "give":{"steel ingot":1}},
        'copper ingot'              : {"craft":10, "take":{"copper bar":5}, "give":{"copper ingot":1}},
        'bronze ingot'              : {"craft":15, "take":{"bronze bar":5}, "give":{"bronze ingot":1}},
        'silver ingot'              : {"craft":10, "take":{"silver bar":5}, "give":{"silver ingot":1}},
        'gold ingot'                : {"craft":15, "take":{"gold bar":5}, "give":{"gold ingot":1}},
        'mythril ingot'             : {"craft":25, "take":{"mytrhril bar":5}, "give":{"mythril ingot":1}},
        'iron bar'                  : {"craft":15, "take":{"iron ingot":1}, "give":{"iron bar":1}},
        'steel bar'                 : {"craft":20, "take":{"steel ingot":1}, "give":{"steel bar":1}},
        'copper bar'                : {"craft":10, "take":{"copper ingot":1}, "give":{"copper bar":1}},
        'bronze bar'                : {"craft":15, "take":{"bronze ingot":1}, "give":{"bronze bar":1}},
        'silver bar'                : {"craft":10, "take":{"silver ingot":1}, "give":{"silver bar":1}},
        'gold bar'                  : {"craft":15, "take":{"gold ingot":1}, "give":{"gold bar":1}},
        'mythril bar'               : {"craft":25, "take":{"mythril ingot":1}, "give":{"mythril bar":1}},
        'iron plate'                : {"craft":15, "take":{"iron bar":1}, "give":{"iron plate":1}},
        'steel plate'               : {"craft":20, "take":{"steel bar":1}, "give":{"steel plate":1}},
        'copper plate'              : {"craft":10, "take":{"copper bar":1}, "give":{"copper plate":1}},
        'bronze plate'              : {"craft":15, "take":{"bronze bar":1}, "give":{"bronze plate":1}},
        'silver plate'              : {"craft":10, "take":{"silver bar":1}, "give":{"silver plate":1}},
        'gold plate'                : {"craft":15, "take":{"gold bar":1}, "give":{"gold plate":1}},
        'mythril plate'             : {"craft":25, "take":{"mytrhril bar":1}, "give":{"mythril plate":1}},
        'iron rod'                  : {"craft":15, "take":{"iron bar":1}, "give":{"iron rod":1}},
        'steel rod'                 : {"craft":20, "take":{"steel bar":1}, "give":{"steel rod":1}},
        'copper rod'                : {"craft":10, "take":{"copper bar":1}, "give":{"copper rod":1}},
        'bronze rod'                : {"craft":15, "take":{"bronze bar":1}, "give":{"bronze rod":1}},
        'silver rod'                : {"craft":10, "take":{"silver bar":1}, "give":{"silver rod":1}},
        'gold rod'                  : {"craft":15, "take":{"gold bar":1}, "give":{"gold rod":1}},
        'mythril rod'               : {"craft":25, "take":{"mytrhril bar":1}, "give":{"mythril rod":1}},
        'spool of iron wire'        : {"craft":15, "take":{"iron ingot":1}, "give":{"spool of iron wire":1}},
        'spool of steel wire'       : {"craft":20, "take":{"steel ingot":1}, "give":{"spool of steel wire":1}},
        'spool of copper wire'      : {"craft":10, "take":{"copper ingot":1}, "give":{"spool of copper wire":1}},
        'spool of bronze wire'      : {"craft":15, "take":{"bronze ingot":1}, "give":{"spool of bronze wire":1}},
        'spool of silver wire'      : {"craft":10, "take":{"silver ingot":1}, "give":{"spool of silver wire":1}},
        'spool of gold wire'        : {"craft":15, "take":{"gold ingot":1}, "give":{"spool of gold wire":1}},
        'spool of mythril wire'     : {"craft":25, "take":{"mytrhril ingot":1}, "give":{"spool of mythril wire":1}},
        'iron wire'                 : {"craft":15, "take":{"iron rod":1}, "give":{"iron wire":1}},
        'steel wire'                : {"craft":20, "take":{"steel rod":1}, "give":{"steel wire":1}},
        'copper wire'               : {"craft":10, "take":{"copper rod":1}, "give":{"copper wire":1}},
        'bronze wire'               : {"craft":15, "take":{"bronze rod":1}, "give":{"bronze wire":1}},
        'silver wire'               : {"craft":10, "take":{"silver rod":1}, "give":{"silver wire":1}},
        'gold wire'                 : {"craft":15, "take":{"gold rod":1}, "give":{"gold wire":1}},
        'mythril wire'              : {"craft":25, "take":{"mytrhril rod":1}, "give":{"mythril wire":1}},
        'iron ring'                 : {"craft":15, "take":{"iron wire":1}, "give":{"iron ring":1}},
        'steel ring'                : {"craft":20, "take":{"steel wire":1}, "give":{"steel ring":1}},
        'copper ring'               : {"craft":10, "take":{"copper wire":1}, "give":{"copper ring":1}},
        'bronze ring'               : {"craft":15, "take":{"bronze wire":1}, "give":{"bronze ring":1}},
        'silver ring'               : {"craft":10, "take":{"silver wire":1}, "give":{"silver ring":1}},
        'gold ring'                 : {"craft":15, "take":{"gold wire":1}, "give":{"gold ring":1}},
        'mythril ring'              : {"craft":25, "take":{"mytrhril wire":1}, "give":{"mythril ring":1}},
        'iron jump rings'           : {"craft":15, "take":{"spool of iron wire":1}, "give":{"iron jump rings":50}},
        'steel jump rings'          : {"craft":20, "take":{"spool of steel wire":1}, "give":{"steel jump rings":50}},
        'copper jump rings'         : {"craft":10, "take":{"spool of copper wire":1}, "give":{"copper jump rings":50}},
        'bronze jump rings'         : {"craft":15, "take":{"spool of bronze wire":1}, "give":{"bronze jump rings":50}},
        'silver jump rings'         : {"craft":10, "take":{"spool of silver wire":1}, "give":{"silver jump rings":50}},
        'gold jump rings'           : {"craft":15, "take":{"spool of gold wire":1}, "give":{"gold jump rings":50}},
        'mythril jump rings'        : {"craft":25, "take":{"spool of mytrhril wire":1}, "give":{"mythril jump rings":50}},
        'cloth'                     : {"craft":15, "take":{"string":8}, "give":{"cloth":1}},
        'rope'                      : {"craft":10, "take":{"string":6}, "give":{"rope":1}},
        'string'                    : {"craft":5, "take":{"flax":10}, "give":{"string":1}},
        
        ## Arms
        
        # Bludgeon
        'club'                       : {"craft":10, "take":{"wood":1}, "give":{"club":1}},
        'club +1'                    : {"craft":15, "take":{"cloth":1, "wood":1}, "give":{"club +1":1}},
        'club +2'                    : {"craft":20, "take":{"ent wood":1}, "give":{"club 2+":1}},
        'spiked club'                : {"craft":15, "take":{"wood":1,"iron rod":1}, "give":{"spiked club":1}},
        'spiked club +1'             : {"craft":20, "take":{"wood":1,"steel rod":1}, "give":{"spiked club +1":1}},
        'spiked club +2'             : {"craft":25, "take":{"ent wood":1,"mythril rod":1}, "give":{"spiked club +2":1}},
        'mace'                       : {"craft":30, "take":{"cloth":1,"wood":1,"iron bar":3}, "give":{"mace":1}},
        'mace +1'                    : {"craft":35, "take":{"cloth":1,"wood":1,"steel bar":3}, "give":{"mace +1":1}},
        'mace +2'                    : {"craft":40, "take":{"cloth":1,"ent wood":1,"mythril bar":3}, "give":{"mace +2":1}},
        'greatmace'                  : {"craft":40, "take":{"cloth":1,"wood":1,"iron bar":6}, "give":{"greatmace":1}},
        'greatmace +1'               : {"craft":45, "take":{"cloth":1,"wood":1,"steel bar":6}, "give":{"greatmace +1":1}},
        'greatmace +2'               : {"craft":50, "take":{"cloth":1,"ent wood":1,"mythril bar":6}, "give":{"greatmace +2":1}},
        'morning star'               : {"craft":40, "take":{"wood":1,"iron ingot":1}, "give":{"morning star":1}},
        'morning star +1'            : {"craft":45, "take":{"wood":1,"steel ingot":1}, "give":{"morning star +1":1}},
        'morning star +2'            : {"craft":50, "take":{"ent wood":1,"mythril ingot":1}, "give":{"morning star +2":1}},
        'war hammer'                 : {"craft":30, "take":{"wood":1,"iron ingot":1}, "give":{"war hammer":1}},
        'war hammer +1'              : {"craft":35, "take":{"wood":1,"steel ingot":1}, "give":{"war hammer +1":1}},
        'war hammer +2'              : {"craft":40, "take":{"ent wood":1,"mythril ingot":1}, "give":{"war hammer +2":1}},
        # Axe
        'war axe'                    : {"craft":40, "take":{"wood":1,"iron ingot":1}, "give":{"war axe":1}},
        'war axe +1'                 : {"craft":45, "take":{"wood":1,"steel ingot":1}, "give":{"war axe +1":1}},
        'war axe +2'                 : {"craft":50, "take":{"ent wood":1,"mythril ingot":1}, "give":{"war axe +2":1}},
        'great war axe'              : {"craft":40, "take":{"wood":1,"iron ingot":1}, "give":{"great war axe":1}},
        'great war axe +1'           : {"craft":45, "take":{"wood":1,"steel ingot":1}, "give":{"great war axe +1":1}},
        'great war axe +2'           : {"craft":50, "take":{"ent wood":1,"mythril ingot":1}, "give":{"great war axe +2":1}},
        'igorot'                     : {"craft":40, "take":{"cloth":1,"wood":1,"iron ingot":1}, "give":{"igorot":1}},
        'igorot +1'                  : {"craft":45, "take":{"cloth":1,"wood":1,"steel ingot":1}, "give":{"igorot +1":1}},
        'igorot +2'                  : {"craft":50, "take":{"cloth":1,"ent wood":1,"mythril ingot":1}, "give":{"igorot +2":1}},
        'lochaber axe'               : {"craft":40, "take":{"wood":1,"iron ingot":1}, "give":{"lochaber axe":1}},
        'lochaber axe +1'            : {"craft":45, "take":{"wood":1,"steel ingot":1}, "give":{"lochaber axe +1":1}},
        'lochaber axe +2'            : {"craft":50, "take":{"ent wood":1,"mythril ingot":1}, "give":{"lochaber axe +2":1}},
        'bardiche'                   : {"craft":40, "take":{"cloth":1,"wood":1,"iron ingot":1}, "give":{"bardiche":1}},
        'bardiche +1'                : {"craft":45, "take":{"cloth":1,"wood":1,"steel ingot":1}, "give":{"bardiche +1":1}},
        'bardiche +2'                : {"craft":50, "take":{"cloth":1,"ent wood":1,"mythril ingot":1}, "give":{"bardiche +2":1}},
        'halberd'                    : {"craft":40, "take":{"wood":1,"iron ingot":1}, "give":{"halberd":1}},
        'halberd +1'                 : {"craft":45, "take":{"wood":1,"steel ingot":1}, "give":{"halberd +1":1}},
        'halberd +2'                 : {"craft":50, "take":{"ent wood":1,"mythril ingot":1}, "give":{"halberd +2":1}},
        # Dagger
        'dagger'                     : {"craft":20, "take":{"string":1,"iron bar":1}, "give":{"dagger":1}},
        'dagger +1'                  : {"craft":25, "take":{"string":1,"steel bar":1}, "give":{"dagger +1":1}},
        'dagger +2'                  : {"craft":30, "take":{"string":1,"mythril bar":1}, "give":{"dagger +2":1}},
        'athame'                     : {"craft":20, "take":{"cloth":1,"iron bar":1}, "give":{"athame":1}},
        'athame +1'                  : {"craft":25, "take":{"cloth":1,"steel bar":1}, "give":{"athame +1":1}},
        'athame +2'                  : {"craft":30, "take":{"cloth":1,"mythril bar":1}, "give":{"athame +2":1}},
        'pugio'                      : {"craft":20, "take":{"leather":1,"iron bar":1}, "give":{"pugio":1}},
        'pugio +1'                   : {"craft":25, "take":{"wyvern hide":1,"steel bar":1}, "give":{"pugio +1":1}},
        'pugio +2'                   : {"craft":30, "take":{"dragon hide":1,"mythril bar":1}, "give":{"pugio +2":1}},
        'cinquedea'                  : {"craft":20, "take":{"cloth":1,"iron bar":1}, "give":{"cinquedea":1}},
        'cinquedea +1'               : {"craft":25, "take":{"cloth":1,"steel bar":1}, "give":{"cinquedea +1":1}},
        'cinquedea +2'               : {"craft":30, "take":{"cloth":1,"mythril bar":1}, "give":{"cinquedea +2":1}},
        'dirk'                       : {"craft":20, "take":{"string":1,"iron bar":1}, "give":{"dirk":1}},
        'dirk +1'                    : {"craft":25, "take":{"string":1,"steel bar":1}, "give":{"dirk +1":1}},
        'dirk +2'                    : {"craft":30, "take":{"string":1,"mythril bar":1}, "give":{"dirk +2":1}},
        'acinaces'                   : {"craft":20, "take":{"wood":1,"iron bar":1}, "give":{"acinaces":1}},
        'acinaces +1'                : {"craft":25, "take":{"wood":1,"steel bar":1}, "give":{"acinaces +1":1}},
        'acinaces +2'                : {"craft":30, "take":{"ent wood":1,"mythril bar":1}, "give":{"acinaces +2":1}},
        'anelace'                    : {"craft":20, "take":{"cloth":1,"iron bar":1}, "give":{"anelace":1}},
        'anelace +1'                 : {"craft":25, "take":{"cloth":1,"steel bar":1}, "give":{"anelace +1":1}},
        'anelace +2'                 : {"craft":30, "take":{"cloth":1,"mythril bar":1}, "give":{"anelace +2":1}},
        # Knife
        'kiridashi'                  : {"craft":20, "take":{"cloth":1,"iron bar":1}, "give":{"kiridashi":1}},
        'kiridashi +1'               : {"craft":25, "take":{"cloth":1,"steel bar":1}, "give":{"kiridashi +1":1}},
        'kiridashi +2'               : {"craft":30, "take":{"cloth":1,"mythril bar":1}, "give":{"kiridashi +2":1}},
        'karambit'                   : {"craft":20, "take":{"string":1,"iron bar":1}, "give":{"karambit":1}},
        'karambit +1'                : {"craft":25, "take":{"string":1,"steel bar":1}, "give":{"karambit +1":1}},
        'karambit +2'                : {"craft":30, "take":{"string":1,"mythril bar":1}, "give":{"karambit +2":1}},
        'puuko'                      : {"craft":20, "take":{"leather":1,"iron bar":1}, "give":{"puuko":1}},
        'puuko +1'                   : {"craft":25, "take":{"wyvern hide":1,"steel bar":1}, "give":{"puuko +1":1}},
        'puuko +2'                   : {"craft":30, "take":{"dragon hide":1,"mythril bar":1}, "give":{"puuko +2":1}},
        'sgian dubh'                 : {"craft":20, "take":{"leather":1,"iron bar":1}, "give":{"sgian dubh":1}},
        'sgian dubh +1'              : {"craft":25, "take":{"wyvern hide":1,"steel bar":1}, "give":{"sgian dubh +1":1}},
        'sgian dubh +2'              : {"craft":30, "take":{"dragon hide":1,"mythril bar":1}, "give":{"sgian dubh +2":1}},
        'tanto'                      : {"craft":20, "take":{"string":1,"iron bar":1}, "give":{"tanto":1}},
        'tanto +1'                   : {"craft":25, "take":{"string":1,"steel bar":1}, "give":{"tanto +1":1}},
        'tanto +2'                   : {"craft":30, "take":{"string":1,"mythril bar":1}, "give":{"tanto +2":1}},
        'kirpan'                     : {"craft":20, "take":{"cloth":1,"iron bar":1}, "give":{"kirpan":1}},
        'kirpan +1'                  : {"craft":25, "take":{"cloth":1,"steel bar":1}, "give":{"kirpan +1":1}},
        'kirpan +2'                  : {"craft":30, "take":{"cloth":1,"mythril bar":1}, "give":{"kirpan +2":1}},
        'seax'                       : {"craft":20, "take":{"wood":1,"iron bar":1}, "give":{"seax":1}},
        'seax +1'                    : {"craft":25, "take":{"wood":1,"steel bar":1}, "give":{"seax +1":1}},
        'seax +2'                    : {"craft":30, "take":{"ent wood":1,"mythril bar":1}, "give":{"seax +2":1}},
        'kukri'                      : {"craft":20, "take":{"cloth":1,"iron bar":1}, "give":{"kukri":1}},
        'kukri +1'                   : {"craft":25, "take":{"cloth":1,"steel bar":1}, "give":{"kukri +1":1}},
        'kukri +2'                   : {"craft":30, "take":{"cloth":1,"mythril bar":1}, "give":{"kukri +2":1}},
        'machete'                    : {"craft":20, "take":{"cloth":1,"iron bar":1}, "give":{"machete":1}},
        'machete +1'                 : {"craft":25, "take":{"cloth":1,"steel bar":1}, "give":{"machete +1":1}},
        'machete +2'                 : {"craft":30, "take":{"cloth":1,"mythril bar":1}, "give":{"machete +2":1}},
        # Sword
        'bastardsword'               : {"craft":40, "take":{"wood":1,"iron ingot":1,"iron bar":1}, "give":{"bastardsword":1}},
        'bastardsword +1'            : {"craft":45, "take":{"wood":1,"steel ingot":1,"steel bar":1}, "give":{"bastardsword +1":1}},
        'bastardsword +2'            : {"craft":50, "take":{"ent wood":1,"mythril ingot":1,"mythril bar":1}, "give":{"bastardsword +2":1}},
        'shortsword'                 : {"craft":40, "take":{"cloth":1,"iron ingot":1,"iron bar":1}, "give":{"shortsword":1}},
        'shortsword +1'              : {"craft":45, "take":{"cloth":1,"steel ingot":1,"steel bar":1}, "give":{"shortsword +1":1}},
        'shortsword +2'              : {"craft":50, "take":{"cloth":1,"mythril ingot":1,"mythril bar":1}, "give":{"shortsword +2":1}},
        'longsword'                  : {"craft":40, "take":{"cloth":1,"iron ingot":1,"iron bar":1}, "give":{"longsword":1}},
        'longsword +1'               : {"craft":45, "take":{"cloth":1,"steel ingot":1,"steel bar":1}, "give":{"longsword +1":1}},
        'longsword +2'               : {"craft":50, "take":{"cloth":1,"mythril ingot":1,"mythril bar":1}, "give":{"longsword +2":1}},
        'rapier'                     : {"craft":40, "take":{"cloth":1,"iron ingot":1,"iron bar":1}, "give":{"rapier":1}},
        'rapier +1'                  : {"craft":45, "take":{"cloth":1,"steel ingot":1,"steel bar":1}, "give":{"rapier +1":1}},
        'rapier +2'                  : {"craft":50, "take":{"cloth":1,"mythril ingot":1,"mythril bar":1}, "give":{"rapier +2":1}},
        'sabre'                      : {"craft":40, "take":{"wood":1,"iron ingot":1,"iron bar":1}, "give":{"sabre":1}},
        'sabre +1'                   : {"craft":45, "take":{"wood":1,"steel ingot":1,"steel bar":1}, "give":{"sabre +1":1}},
        'sabre +2'                   : {"craft":50, "take":{"ent wood":1,"mythril ingot":1,"mythril bar":1}, "give":{"sabre +2":1}},
        'falchion'                   : {"craft":40, "take":{"wood":1,"iron ingot":1,"iron bar":1}, "give":{"falchion":1}},
        'falchion +1'                : {"craft":45, "take":{"wood":1,"steel ingot":1,"steel bar":1}, "give":{"falchion +1":1}},
        'falchion +2'                : {"craft":50, "take":{"ent wood":1,"mythril ingot":1,"mythril bar":1}, "give":{"falchion +2":1}},
        'scimitar'                   : {"craft":40, "take":{"cloth":1,"iron ingot":1,"iron bar":1}, "give":{"scimitar":1}},
        'scimitar +1'                : {"craft":45, "take":{"cloth":1,"steel ingot":1,"steel bar":1}, "give":{"scimitar +1":1}},
        'scimitar +2'                : {"craft":50, "take":{"cloth":1,"mythril ingot":1,"mythril bar":1}, "give":{"scimitar +2":1}},
        'kopesh'                     : {"craft":40, "take":{"cloth":1,"iron ingot":1,"iron bar":1}, "give":{"kopesh":1}},
        'kopesh +1'                  : {"craft":45, "take":{"cloth":1,"steel ingot":1,"steel bar":1}, "give":{"kopesh +1":1}},
        'kopesh +2'                  : {"craft":50, "take":{"cloth":1,"mythril ingot":1,"mythril bar":1}, "give":{"kopesh +2":1}},
        'kopis'                      : {"craft":40, "take":{"cloth":1,"iron ingot":1,"iron bar":1}, "give":{"kopis":1}},
        'kopis +1'                   : {"craft":45, "take":{"cloth":1,"steel ingot":1,"steel bar":1}, "give":{"kopis +1":1}},
        'kopis +2'                   : {"craft":50, "take":{"cloth":1,"mythril ingot":1,"mythril bar":1}, "give":{"kopis +2":1}},
        'katana'                     : {"craft":40, "take":{"string":1,"iron ingot":1,"iron bar":1}, "give":{"katana":1}},
        'katana +1'                  : {"craft":45, "take":{"string":1,"steel ingot":1,"steel bar":1}, "give":{"katana +1":1}},
        'katana +2'                  : {"craft":50, "take":{"string":1,"mythril ingot":1,"mythril bar":1}, "give":{"katana +2":1}},
        # Great Sword
        'uchigatana'                 : {"craft":40, "take":{"string":1,"iron ingot":2,"iron bar":1}, "give":{"uchigatana":1}},
        'uchigatana +1'              : {"craft":45, "take":{"string":1,"steel ingot":2,"steel bar":1}, "give":{"uchigatana +1":1}},
        'uchigatana +2'              : {"craft":50, "take":{"string":1,"mythril ingot":2,"mythril bar":1}, "give":{"uchigatana +2":1}},
        'greatsword'                 : {"craft":40, "take":{"cloth":1,"iron ingot":2,"iron bar":1}, "give":{"greatsword":1}},
        'greatsword +1'              : {"craft":45, "take":{"cloth":1,"steel ingot":2,"steel bar":1}, "give":{"greatsword +1":1}},
        'greatsword +2'              : {"craft":50, "take":{"cloth":1,"mythril ingot":2,"mythril bar":1}, "give":{"greatsword +2":1}},
        'claymore'                   : {"craft":40, "take":{"wood":1,"iron ingot":2,"iron bar":1}, "give":{"claymore":1}},
        'claymore +1'                : {"craft":45, "take":{"wood":1,"steel ingot":2,"steel bar":1}, "give":{"claymore +1":1}},
        'claymore +2'                : {"craft":50, "take":{"ent wood":1,"mythril ingot":2,"mythril bar":1}, "give":{"claymore +2":1}},
        'flamberge'                  : {"craft":40, "take":{"cloth":1,"iron ingot":2,"iron bar":1}, "give":{"flamberge":1}},
        'flamberge +1'               : {"craft":45, "take":{"cloth":1,"steel ingot":2,"steel bar":1}, "give":{"flamberge +1":1}},
        'flamberge +2'               : {"craft":50, "take":{"cloth":1,"mythril ingot":2,"mythril bar":1}, "give":{"flamberge +2":1}},
        # Polearm
        'hunting spear'              : {"craft":10, "take":{"string":1,"wood":1,"iron bar":1}, "give":{"hunting spear":1}},
        'hunting spear +1'           : {"craft":15, "take":{"string":1,"wood":1,"steel bar":1}, "give":{"hunting spear +1":1}},
        'hunting spear +2'           : {"craft":20, "take":{"string":1,"ent wood":1,"mythril bar":1}, "give":{"hunting spear +2":1}},
        'spear'                      : {"craft":10, "take":{"wood":1,"iron bar":1}, "give":{"spear":1}},
        'spear +1'                   : {"craft":15, "take":{"wood":1,"steel bar":1}, "give":{"spear +1":1}},
        'spear +2'                   : {"craft":20, "take":{"ent wood":1,"mythril bar":1}, "give":{"spear +2":1}},
        'pike'                       : {"craft":20, "take":{"wood":1,"iron bar":2}, "give":{"pike":1}},
        'pike +1'                    : {"craft":25, "take":{"wood":1,"steel bar":2}, "give":{"pike +1":1}},
        'pike +2'                    : {"craft":30, "take":{"ent wood":1,"mythril bar":2}, "give":{"pike +2":1}},
        'lance'                      : {"craft":20, "take":{"wood":1,"iron bar":3}, "give":{"lance":1}},
        'lance +1'                   : {"craft":25, "take":{"wood":1,"steel bar":3}, "give":{"lance +1":1}},
        'lance +2'                   : {"craft":30, "take":{"ent wood":1,"mythril bar":3}, "give":{"lance +2":1}},
        'voulge'                     : {"craft":20, "take":{"wood":1,"iron bar":3}, "give":{"voulge":1}},
        'voulge +1'                  : {"craft":25, "take":{"wood":1,"steel bar":3}, "give":{"voulge +1":1}},
        'voulge +2'                  : {"craft":30, "take":{"ent wood":1,"mythril bar":3}, "give":{"voulge +2":1}},
        # Shield
        'buckler'                    : {"craft":10, "take":{"wood":1,"iron bar":1}, "give":{"buckler":1}},
        'buckler +1'                 : {"craft":15, "take":{"wood":1,"steel bar":1}, "give":{"buckler +1":1}},
        'buckler +2'                 : {"craft":20, "take":{"ent wood":1,"mythril bar":1}, "give":{"buckler +2":1}},
        'shield'                     : {"craft":10, "take":{"wood":1,"iron bar":2}, "give":{"shield":1}},
        'shield +1'                  : {"craft":15, "take":{"wood":1,"steel bar":2}, "give":{"shield +1":1}},
        'shield +2'                  : {"craft":20, "take":{"ent wood":1,"mythril bar":2}, "give":{"shield +2":1}},
        'tower shield'               : {"craft":20, "take":{"cloth":1,"wood":2,"iron ingot":1}, "give":{"tower shield":1}},
        'tower shield +1'            : {"craft":25, "take":{"cloth":1,"wood":2,"steel ingot":1}, "give":{"tower shield +1":1}},
        'tower shield +2'            : {"craft":30, "take":{"cloth":1,"ent wood":2,"mythril ingot":1}, "give":{"tower shield +2":1}},
        # Ranged
        'flintlock pistol'           : {"craft":70, "take":{"iron ingot":1,"iron bar":1,"iron rod":1}, "give":{"flintlock pistol":1}},
        'flintlock pistol +1'        : {"craft":80, "take":{"steel ingot":1,"steel bar":1,"steel rod":1}, "give":{"flintlock pistol +1":1}},
        'flintlock pistol +2'        : {"craft":90, "take":{"mythril ingot":1,"mythril bar":1,"mythril rod":1}, "give":{"flintlock pistol +2":1}},
        'revolver'                   : {"craft":80, "take":{"iron ingot":1,"iron bar":2,"iron rod":1}, "give":{"revolver":1}},
        'revolver +1'                : {"craft":90, "take":{"steel ingot":1,"steel bar":2,"steel rod":1}, "give":{"revolver +1":1}},
        'revolver +2'                : {"craft":100, "take":{"mythril ingot":1,"mythril bar":2,"mythril rod":1}, "give":{"revolver +2":1}},
        'flintlock rifle'            : {"craft":70, "take":{"wood":1,"iron ingot":1,"iron bar":1,"iron rod":2}, "give":{"flintlock rifle":1}},
        'flintlock rifle +1'         : {"craft":80, "take":{"wood":1,"steel ingot":1,"steel bar":1,"steel rod":2}, "give":{"flintlock rifle +1":1}},
        'flintlock rifle +2'         : {"craft":90, "take":{"wood":1,"mythril ingot":1,"mythril bar":1,"mythril rod":2}, "give":{"flintlock rifle +2":1}},
        'revolver rifle'             : {"craft":80, "take":{"wood":1,"iron ingot":1,"iron bar":2,"iron rod":2}, "give":{"revolver rifle":1}},
        'revolver rifle +1'          : {"craft":90, "take":{"wood":1,"steel ingot":1,"steel bar":2,"steel rod":2}, "give":{"revolver rifle +1":1}},
        'revolver rifle +2'          : {"craft":100, "take":{"wood":1,"mythril ingot":1,"mythril bar":2,"mythril rod":2}, "give":{"revolver rifle +2":1}},
        
        
        
		## Armor
        
        # Necklace
        'necklace'                   : {"craft":30, "take":{"gold jump rings":1}, "give":{"necklace":1}},
        'magic necklace'             : {"craft":50, "take":{"silver jump rings":1,"spool of mythril wire":1}, "give":{"magic necklace":1}},
        'magic necklace +1'          : {"craft":60, "take":{"gold jump rings":1,"spool of mythril wire":1}, "give":{"magic necklace +1":1}},
        'magic necklace +2'          : {"craft":70, "take":{"mythril jump rings":1,"spool of mythril wire":1}, "give":{"magic necklace +2":1}},
        'blessed necklace'           : {"craft":80, "take":{"silver jump rings":1,"spool of mythril wire":1}, "give":{"blessed necklace":1}},
        'blessed necklace +1'        : {"craft":90, "take":{"gold jump rings":1,"spool of mythril wire":1}, "give":{"blessed necklace +1":1}},
        'blessed necklace +2'        : {"craft":100, "take":{"mythril jump rings":1,"spool of mythril wire":1}, "give":{"blessed necklace +2":1}},
        # Rings
        'ring'                       : {"craft":30, "take":{"gold ring":1}, "give":{"ring":1}},
        'magic ring'                 : {"craft":50, "take":{"silver ring":1,"mythril wire":1}, "give":{"magic ring":1}},
        'magic ring +1'              : {"craft":60, "take":{"gold ring":1,"mythril wire":1}, "give":{"magic ring +1":1}},
        'magic ring +2'              : {"craft":70, "take":{"mythril ring":1,"mythril wire":1}, "give":{"magic ring +2":1}},
        'blessed ring'               : {"craft":80, "take":{"silver ring":1,"mythril wire":2}, "give":{"blessed ring":1}},
        'blessed ring +1'            : {"craft":90, "take":{"gold ring":1,"mythril wire":2}, "give":{"blessed ring +1":1}},
        'blessed ring +2'            : {"craft":100, "take":{"mythril ring":1,"mythril wire":2}, "give":{"blessed ring +2":1}},
        
        # Head
        'coif'                       : {"craft":30, "take":{"iron jump rings":5}, "give":{"coif":1}},
        'coif +1'                    : {"craft":40, "take":{"steel jump rings":5}, "give":{"coif +1":1}},
        'coif +2'                    : {"craft":50, "take":{"mythril jump rings":5}, "give":{"coif +2":1}},
        'cervelliere'                : {"craft":30, "take":{"iron plate":1}, "give":{"cervelliere":1}},
        'cervelliere +1'             : {"craft":40, "take":{"steel plate":1}, "give":{"cervelliere +1":1}},
        'cervelliere +2'             : {"craft":50, "take":{"mythril plate":1}, "give":{"cervelliere +2":1}},
        'nasal helm'                 : {"craft":20, "take":{"iron plate":1}, "give":{"nasal helm":1}},
        'nasal helm +1'              : {"craft":30, "take":{"steel plate":1}, "give":{"nasal helm +1":1}},
        'nasal helm +2'              : {"craft":40, "take":{"mythril plate":1}, "give":{"nasal helm +2":1}},
        'sallet'                     : {"craft":30, "take":{"iron plate":1}, "give":{"sallet":1}},
        'sallet +1'                  : {"craft":40, "take":{"steel plate":1}, "give":{"sallet +1":1}},
        'sallet +2'                  : {"craft":50, "take":{"mythril plate":1}, "give":{"sallet +2":1}},
        'barbute'                    : {"craft":30, "take":{"iron plate":1}, "give":{"barbute":1}},
        'barbute +1'                 : {"craft":40, "take":{"steel plate":1}, "give":{"barbute +1":1}},
        'barbute +2'                 : {"craft":50, "take":{"mythril plate":1}, "give":{"barbute +2":1}},
        'greathelm'                  : {"craft":40, "take":{"iron plate":1}, "give":{"greathelm":1}},
        'greathelm +1'               : {"craft":50, "take":{"steel plate":1}, "give":{"greathelm +1":1}},
        'greathelm +2'               : {"craft":60, "take":{"mythril plate":1}, "give":{"greathelm +2":1}},
        'bassinet'                   : {"craft":40, "take":{"iron plate":1}, "give":{"bassinet":1}},
        'bassinet +1'                : {"craft":50, "take":{"steel plate":1}, "give":{"bassinet +1":1}},
        'bassinet +2'                : {"craft":60, "take":{"mythril plate":1}, "give":{"bassinet +2":1}},
        'close helm'                 : {"craft":40, "take":{"iron plate":1}, "give":{"close helm":1}},
        'close helm +1'              : {"craft":50, "take":{"steel plate":1}, "give":{"close helm +1":1}},
        'close helm +2'              : {"craft":60, "take":{"mythril plate":1}, "give":{"close helm +2":1}},
        # Neck
        'cloak'                      : {"craft":30, "take":{"cloth":5}, "give":{"cloak":1}},
        'bevor'                      : {"craft":30, "take":{"iron plate":1}, "give":{"bevor":1}},
        'bevor +1'                   : {"craft":40, "take":{"steel plate":1}, "give":{"bevor +1":1}},
        'bevor +2'                   : {"craft":50, "take":{"mythril plate":1}, "give":{"bevor +2":1}},
        'gorget'                     : {"craft":30, "take":{"iron plate":1}, "give":{"gorget":1}},
        'gorget +1'                  : {"craft":40, "take":{"steel plate":1}, "give":{"gorget +1":1}},
        'gorget +2'                  : {"craft":50, "take":{"mythril plate":1}, "give":{"gorget +2":1}},
        # Shoulders
        'spaulders'                  : {"craft":20, "take":{"iron plate":1}, "give":{"spaulders":1}},
        'spaulders +1'               : {"craft":30, "take":{"steel plate":1}, "give":{"spaulders +1":1}},
        'spaulders +2'               : {"craft":40, "take":{"mythril plate":1}, "give":{"spaulders +2":1}},
        'pauldrons'                  : {"craft":20, "take":{"iron plate":1}, "give":{"pauldrons":1}},
        'pauldrons +1'               : {"craft":30, "take":{"steel plate":1}, "give":{"pauldrons +1":1}},
        'pauldrons +2'               : {"craft":40, "take":{"mythril plate":1}, "give":{"pauldrons +2":1}},
        # Torso
        'shirt'                      : {"craft":30, "take":{"cloth":3}, "give":{"shirt":1}},
        'ringmail'                   : {"craft":20, "take":{"iron ring":10}, "give":{"ringmail":1}},
        'ringmail +1'                : {"craft":30, "take":{"steel ring":10}, "give":{"ringmail +1":1}},
        'ringmail +2'                : {"craft":40, "take":{"mythril ring":10}, "give":{"ringmail +2":1}},
        'scalemail'                  : {"craft":30, "take":{"iron jump rings":10}, "give":{"scalemail":1}},
        'scalemail +1'               : {"craft":40, "take":{"steel jump rings":10}, "give":{"scalemail +1":1}},
        'scalemail +2'               : {"craft":50, "take":{"mythril jump rings":10}, "give":{"scalemail +2":1}},
        'hauberk'                    : {"craft":30, "take":{"iron jump rings":25}, "give":{"hauberk":1}},
        'hauberk +1'                 : {"craft":40, "take":{"steel jump rings":25}, "give":{"hauberk +1":1}},
        'hauberk +2'                 : {"craft":50, "take":{"mythril jump rings":25}, "give":{"hauberk +2":1}},
        'breastplate'                : {"craft":40, "take":{"iron plate":1}, "give":{"breastplate":1}},
        'breastplate +1'             : {"craft":50, "take":{"steel plate":1}, "give":{"breastplate +1":1}},
        'breastplate +2'             : {"craft":60, "take":{"mythril plate":1}, "give":{"breastplate +2":1}},
        'coat of plates'             : {"craft":30, "take":{"iron plate":1}, "give":{"coat of plates":1}},
        'coat of plates +1'          : {"craft":40, "take":{"steel plate":1}, "give":{"coat of plates +1":1}},
        'coat of plates +2'          : {"craft":50, "take":{"mythril plate":1}, "give":{"coat of plates +2":1}},
        'cuirass'                    : {"craft":40, "take":{"iron plate":1}, "give":{"cuirass":1}},
        'cuirass +1'                 : {"craft":50, "take":{"steel plate":1}, "give":{"cuirass +1":1}},
        'cuirass +2'                 : {"craft":60, "take":{"mythril plate":1}, "give":{"cuirass +2":1}},
        'leather cuirass'            : {"craft":30, "take":{"leather":1}, "give":{"leather cuirass":1}},
        'leather cuirass +1'         : {"craft":40, "take":{"wyvern hide":1}, "give":{"leather cuirass +1":1}},
        'leather cuirass +2'         : {"craft":50, "take":{"dragon hide":1}, "give":{"leather cuirass +2":1}},
        'studded leather cuirass'    : {"craft":40, "take":{"leather":1}, "give":{"studded leather cuirass":1}},
        'studded leather cuirass +1' : {"craft":50, "take":{"wyvern hide":1}, "give":{"studded leather cuirass +1":1}},
        'studded leather cuirass +2' : {"craft":60, "take":{"dragon hide":1}, "give":{"studded leather cuirass +2":1}},
        # Waist
        'belt'                       : {"craft":10, "take":{"leather":1}, "give":{"belt":1}},
        'chainskirt'                 : {"craft":20, "take":{"iron jump rings":10}, "give":{"chainskirt":1}},
        'chainskirt +1'              : {"craft":30, "take":{"steel jump rings":10}, "give":{"chainskirt +1":1}},
        'chainskirt +2'              : {"craft":40, "take":{"mythril jump rings":10}, "give":{"chainskirt +2":1}},
        'tassets'                    : {"craft":20, "take":{"iron plate":1}, "give":{"tassets":1}},
        'tassets +1'                 : {"craft":30, "take":{"steel plate":1}, "give":{"tassets +1":1}},
        'tassets +2'                 : {"craft":40, "take":{"mythril plate":1}, "give":{"tassets +2":1}},
        'fauld'                      : {"craft":20, "take":{"iron plate":1}, "give":{"fauld":1}},
        'fauld +1'                   : {"craft":30, "take":{"steel plate":1}, "give":{"fauld +1":1}},
        'fauld +2'                   : {"craft":40, "take":{"mythril plate":1}, "give":{"fauld +2":1}},
        # Arms
        'bracers'                    : {"craft":20, "take":{"iron plate":1}, "give":{"bracers":1}},
        'bracers +1'                 : {"craft":30, "take":{"steel plate":1}, "give":{"bracers +1":1}},
        'bracers +2'                 : {"craft":40, "take":{"mythril plate":1}, "give":{"bracers +2":1}},
        'vambrace'                   : {"craft":20, "take":{"iron plate":1}, "give":{"vambrace":1}},
        'vambrace +1'                : {"craft":30, "take":{"steel plate":1}, "give":{"vambrace +1":1}},
        'vambrace +2'                : {"craft":40, "take":{"mythril plate":1}, "give":{"vambrace +2":1}},
        'rerebrace'                  : {"craft":20, "take":{"iron plate":1}, "give":{"rerebrace":1}},
        'rerebrace +1'               : {"craft":30, "take":{"steel plate":1}, "give":{"rerebrace +1":1}},
        'rerebrace +2'               : {"craft":40, "take":{"mythril plate":1}, "give":{"rerebrace +2":1}},
        'full cannon'                : {"craft":30, "take":{"iron plate":1}, "give":{"full cannon":1}},
        'full cannon +1'             : {"craft":40, "take":{"steel plate":1}, "give":{"full cannon +1":1}},
        'full cannon +2'             : {"craft":50, "take":{"mythril plate":1}, "give":{"full cannon +2":1}},
        # Legs
        'pants'                      : {"craft":20, "take":{"cloth":4}, "give":{"pants":1}},
        'cuisse'                     : {"craft":20, "take":{"iron plate":1}, "give":{"cuisse":1}},
        'cuisse +1'                  : {"craft":30, "take":{"steel plate":1}, "give":{"cuisse +1":1}},
        'cuisse +2'                  : {"craft":40, "take":{"mythril plate":1}, "give":{"cuisse +2":1}},
        'poleyn'                     : {"craft":20, "take":{"iron plate":1}, "give":{"poleyn":1}},
        'poleyn +1'                  : {"craft":30, "take":{"steel plate":1}, "give":{"poleyn +1":1}},
        'poleyn +2'                  : {"craft":40, "take":{"mythril plate":1}, "give":{"poleyn +2":1}},
        'chausses'                   : {"craft":30, "take":{"iron plate":1}, "give":{"chausses":1}},
        'chausses +1'                : {"craft":40, "take":{"steel plate":1}, "give":{"chausses +1":1}},
        'chausses +2'                : {"craft":50, "take":{"mythril plate":1}, "give":{"chausses +2":1}},
        # Hands
        'gloves'                     : {"craft":30, "take":{"leather":1}, "give":{"gloves":1}},
        'gloves +1'                  : {"craft":40, "take":{"wyvern hide":1}, "give":{"gloves +1":1}},
        'gloves +2'                  : {"craft":50, "take":{"dragon hide":1}, "give":{"gloves +2":1}},
        'chain gloves'               : {"craft":30, "take":{"gloves":1,"iron jump rings":5}, "give":{"chain gloves":1}},
        'chain gloves +1'            : {"craft":40, "take":{"gloves +1":1,"steel jump rings":5}, "give":{"chain gloves +1":1}},
        'chain gloves +2'            : {"craft":50, "take":{"gloves +2":1,"mythril jump rings":5}, "give":{"chain gloves +2":1}},
        'gauntlets'                  : {"craft":40, "take":{"gloves":1,"iron plate":1}, "give":{"gauntlets":1}},
        'gauntlets +1'               : {"craft":50, "take":{"gloves +1":1,"steel plate":1}, "give":{"gauntlets +1":1}},
        'gauntlets +2'               : {"craft":60, "take":{"gloves +2":1,"mythril plate":1}, "give":{"gauntlets +2":1}},
        'fanged gauntlets'           : {"craft":50, "take":{"gloves":1,"gargoyle fang":8,"gauntlets":1}, "give":{"fanged gauntlets":1}},
        'fanged gauntlets +1'        : {"craft":60, "take":{"gloves +1":1,"wyvern fang":8,"gauntlets +1":1}, "give":{"fanged gauntlets +1":1}},
        'fanged gauntlets +2'        : {"craft":70, "take":{"gloves +2":1,"dragon fang":8,"gauntlets +2":1}, "give":{"fanged gauntlets +2":1}},
        # Feet
        'boots'                      : {"craft":30, "take":{"leather":1}, "give":{"boots":1}},
        'boots +1'                   : {"craft":40, "take":{"wyvern hide":1}, "give":{"boots +1":1}},
        'boots +2'                   : {"craft":50, "take":{"dragon hide":1}, "give":{"boots +2":1}},
        'chain boots'                : {"craft":30, "take":{"boots":1,"iron jump rings":5}, "give":{"chain boots":1}},
        'chain boots +1'             : {"craft":40, "take":{"boots +1":1,"steel jump rings":5}, "give":{"chain boots +1":1}},
        'chain boots +2'             : {"craft":50, "take":{"boots +2":1,"mythril jump rings":5}, "give":{"chain boots +2":1}},
        'sabatons'                   : {"craft":30, "take":{"boots":1,"iron plate":1}, "give":{"sabatons":1}},
        'sabatons +1'                : {"craft":40, "take":{"boots +1":1,"steel plate":1}, "give":{"sabatons +1":1}},
        'sabatons +2'                : {"craft":50, "take":{"boots +2":1,"mythril plate":1}, "give":{"sabatons +2":1}},
        'greaves'                    : {"craft":30, "take":{"boots":1,"iron plate":2}, "give":{"greaves":1}},
        'greaves +1'                 : {"craft":40, "take":{"boots +1":1,"steel plate":2}, "give":{"greaves +1":1}},
        'greaves +2'                 : {"craft":50, "take":{"boots +2":1,"mythril plate":2}, "give":{"greaves +2":1}},
        'full greaves'               : {"craft":40, "take":{"boots":1,"iron plate":3}, "give":{"full greaves":1}},
        'full greaves +1'            : {"craft":50, "take":{"boots +1":1,"steel plate":3}, "give":{"full greaves +1":1}},
        'full greaves +2'            : {"craft":60, "take":{"boots +2":1,"mythril plate":3}, "give":{"full greaves +2":1}},
    }
